### ISSUE TITLE
OPT-175B Inference  - Error while running the API

### ISSUE THREAD

**Issue by BalajiAJ** [facebookresearch/metaseq#155]
#### What is your question?
We have A100 40GB GPU's and trying to run the 175B model from OPT. We followed the instructions from [58](https://github.com/facebookresearch/metaseq/issues/58) by keeping MP to 8 and DP to 2 (16 shards) in the following command.  

We are seeing errors related to Model parallelism while running the API - _'intra_layer_model parallel group is not initialized'_
```
!bash reshard_mp_launch_no_slurm.sh 
/home/user1/metaseq/metaseq/scripts/checkpoint_last 
/home/user1/metaseq/metaseq/scripts/reshard/ 8 2
```
Files under **_reshard_** folder has been saved as:
```
reshard-model_part-0-shard0.pt
reshard-model_part-0-shard1.pt
reshard-model_part-1-shard0.pt
reshard-model_part-1-shard1.pt  .....
```

#### Code

```
metaseq-api-local
```
#### What have you tried?

In constants.py, we have set MODEL_PARALLEL to  **8** and TOTAL_WORLD_SIZE to **16** and ran the API command

##### Error:
  File "/home/user1/Megatron-LM/megatron/mpu/initialize.py", line 216, in get_tensor_model_parallel_group
    'intra_layer_model parallel group is not initialized'

#### What's your environment?

 - metaseq Version (e.g., 1.0 or master): 
 - PyTorch Version (e.g., 1.0):  
 - OS (e.g., Linux):  Linux
 - How you installed metaseq (`pip`, source):  source
 - Build command you used (if compiling from source): Referred this link : [setup](https://github.com/facebookresearch/metaseq/blob/main/docs/setup.md)
 - Python version:  3.7.12
 - CUDA/cuDNN version: 11.2
 - GPU models and configuration: 16 A100 40GB
 - Any other relevant information:

**Comment by suchenzang** [comment]
@BalajiAJ can you past the full stacktrace for your error above?

**Comment by BalajiAJ** [comment]
> user1

```
2022-06-17 08:25:33 | INFO | metaseq.checkpoint_utils | Done reading from disk
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user1/metaseq/metaseq_cli/interactive_hosted.py", line 300, in <module>
    cli_main()
  File "/home/user1/metaseq/metaseq_cli/interactive_hosted.py", line 296, in cli_main
    dist_utils.call_main(cfg, worker_main, namespace_args=args)
  File "/home/user1/metaseq/metaseq/distributed/utils.py", line 263, in call_main
    return main(cfg, **kwargs)
  File "/home/user1/metaseq/metaseq_cli/interactive_hosted.py", line 156, in worker_main
    models = generator.load_model()  # noqa: F841
  File "/home/user1/metaseq/metaseq/hub_utils.py", line 492, in load_model
    build_model_hook=_build_model,
  File "/home/user1/metaseq/metaseq/checkpoint_utils.py", line 517, in load_model_ensemble_and_task
    model = build_model_hook(cfg, task)
  File "/home/user1/metaseq/metaseq/hub_utils.py", line 474, in _build_model
    model = task.build_model(cfg.model).half().cuda()
  File "/home/user1/metaseq/metaseq/tasks/base_task.py", line 560, in build_model
    model = models.build_model(args, self)
  File "/home/user1/metaseq/metaseq/models/__init__.py", line 89, in build_model
    return model.build_model(cfg, task)
  File "/home/user1/metaseq/metaseq/model_parallel/models/transformer_lm.py", line 49, in build_model
    args, task.source_dictionary, args.decoder_input_dim
  File "/home/user1/metaseq/metaseq/model_parallel/models/transformer_lm.py", line 94, in build_embedding
    dtype=dtype,
  File "/home/user1/Megatron-LM/megatron/mpu/layers.py", line 190, in __init__
    self.tensor_model_parallel_size = get_tensor_model_parallel_world_size()
  File "/home/user1/Megatron-LM/megatron/mpu/initialize.py", line 258, in get_tensor_model_parallel_world_size
    return torch.distributed.get_world_size(group=get_tensor_model_parallel_group())
  File "/home/user1/Megatron-LM/megatron/mpu/initialize.py", line 216, in get_tensor_model_parallel_group
    'intra_layer_model parallel group is not initialized'
AssertionError: intra_layer_model parallel group is not initialized
```

**Comment by suchenzang** [comment]
@BalajiAJ Can you add some debug statements around https://github.com/ngoyal2707/Megatron-LM/blob/91a7a360d3b6fb2cb425abf2220279a3582a7a71/megatron/mpu/initialize.py#L151 ? Would like to see what `num_tensor_model_parallel_groups` is here.

**Comment by BalajiAJ** [comment]
> @BalajiAJ Can you add some debug statements around https://github.com/ngoyal2707/Megatron-LM/blob/91a7a360d3b6fb2cb425abf2220279a3582a7a71/megatron/mpu/initialize.py#L151 ? Would like to see what `num_tensor_model_parallel_groups` is here.

```
2022-06-17 11:21:27 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:12 to store for rank: 0
num_tensor_model_parallel_groups.... 2
num_tensor_model_parallel_groups.... 2
num_tensor_model_parallel_groups.... 2
num_tensor_model_parallel_groups.... 2
num_tensor_model_parallel_groups.... 2
num_tensor_model_parallel_groups.... 2
2022-06-17 11:21:27 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:12 with 16 nodes.
2022-06-17 11:21:27 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:13 to store for rank: 0
post for loop... <torch._C._distributed_c10d.ProcessGroupNCCL object at 0x7f5b50093930>
post for loop... <torch._C._distributed_c10d.ProcessGroupNCCL object at 0x7f46163da870>
post for loop... <torch._C._distributed_c10d.ProcessGroupNCCL object at 0x7f04b0014770>
2022-06-17 11:21:27 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:13 with 16 nodes.
```

**Comment by stephenroller** [comment]
We're working on adding support for running over 2 nodes. Main thread is #131.

Your particular error is probably because the launcher uses the wrong `-n / --ntasks`.
