### ISSUE TITLE
Error after setup when trying to run API

### ISSUE THREAD

**Issue by jminjie** [facebookresearch/metaseq#23]
## ❓ Questions and Help

After following setup steps I ran `metaseq-api-local` and got this output:
```
$ metaseq-api-local
Traceback (most recent call last):
  File "/home/jliu/openpretrainedtransformer/metaseq/metaseq/service/constants.py", line 17, in <module>
    from metaseq_internal.constants import LOCAL_SSD, MODEL_SHARED_FOLDER
ModuleNotFoundError: No module named 'metaseq_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jliu/miniconda3/envs/conda_env_opt/bin/metaseq-api-local", line 33, in <module>
    sys.exit(load_entry_point('metaseq', 'console_scripts', 'metaseq-api-local')())
  File "/home/jliu/miniconda3/envs/conda_env_opt/bin/metaseq-api-local", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/jliu/openpretrainedtransformer/metaseq/metaseq_cli/interactive_hosted.py", line 31, in <module>
    from metaseq.service.constants import (
  File "/home/jliu/openpretrainedtransformer/metaseq/metaseq/service/constants.py", line 40, in <module>
    raise RuntimeError(
RuntimeError: You must set the variables in metaseq.service.constants to launch the API.
```
Am I missing a step? I tried manually setting LOCAL_SSD, MODEL_SHARED_FOLDER to a new folder I created but then other things failed.

 - fairseq Version (e.g., 1.0 or master): followed setup.md
 - PyTorch Version (e.g., 1.0) followed setup.md
 - OS (e.g., Linux): Ubuntu
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): followed setup.md
 - Python version: 3.9.12
 - CUDA/cuDNN version: 11.3
 - GPU models and configuration: Quadro RTX 5000
 - Any other relevant information:

**Comment by jminjie** [comment]
1546035 doesn't seem to fix this issue (I tried it locally).

**Comment by stephenroller** [comment]
Can you share with me how you have set things?

**Comment by jminjie** [comment]
Sure. I have multiple CUDA versions installed, so I'm using a conda virtual environment set to use CUDA 11.3 on an Ubuntu machine with an Nvidia Quadro RTX 5000. I installed PyTorch, Apex, Megatron, fairscale, and metaseq using the instructions on setup.md. Now I'm trying to run metaseq-api-local and seeing errors.

(I'm also not sure if the intention is that I can run the API right away, or if I need to download weights or something somewhere first)

**Comment by jminjie** [comment]
(This issue is not resolved btw)

I'll try to reproduce again. Let me know if there's any specifics about my setup that you need.

**Comment by hunterlang** [comment]
I had the same problems and got a few steps farther by directly modifying `MODEL_SHARED_FOLDER` and `LOCAL_SSD` inside `constants.py`.

**Comment by jminjie** [comment]
Yes I tried just creating the needed folders but then started seeing more errors.

```
(conda_env_opt) [~/fbopt/metaseq]$ metaseq-api-local
2022-05-03 16:23:01 | INFO | metaseq_cli.interactive | Local checkpoint copy already exists, skipping copy
2022-05-03 16:23:01 | INFO | metaseq_cli.interactive | Hackishly generated a dict.txt for use with 175B model
2022-05-03 16:23:02 | INFO | metaseq.tasks.language_modeling | dictionary: 50272 types
2022-05-03 16:23:02 | INFO | metaseq.hub_utils | loading model(s) from /home/jliu/fbopt/storage/175B/reshard_no_os/reshard.pt
Traceback (most recent call last):
  File "/home/jliu/miniconda3/envs/conda_env_opt/bin/metaseq-api-local", line 33, in <module>
    sys.exit(load_entry_point('metaseq', 'console_scripts', 'metaseq-api-local')())
  File "/home/jliu/fbopt/metaseq/metaseq_cli/interactive_hosted.py", line 300, in cli_main
    dist_utils.call_main(cfg, worker_main, namespace_args=args)
  File "/home/jliu/fbopt/metaseq/metaseq/distributed/utils.py", line 226, in call_main
    main(cfg, **kwargs)
  File "/home/jliu/fbopt/metaseq/metaseq_cli/interactive_hosted.py", line 156, in worker_main
    models = generator.load_model()  # noqa: F841
  File "/home/jliu/fbopt/metaseq/metaseq/hub_utils.py", line 485, in load_model
    models, _model_args, _task = checkpoint_utils.load_model_ensemble_and_task(
  File "/home/jliu/fbopt/metaseq/metaseq/checkpoint_utils.py", line 473, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/jliu/fbopt/metaseq/metaseq/checkpoint_utils.py", line 408, in load_checkpoint_to_cpu
    paths_to_load = get_paths_to_load(local_path, suffix="shard")
  File "/home/jliu/fbopt/metaseq/metaseq/checkpoint_utils.py", line 348, in get_paths_to_load
    if not _is_checkpoint_sharded(checkpoint_files):
  File "/home/jliu/fbopt/metaseq/metaseq/checkpoint_utils.py", line 339, in _is_checkpoint_sharded
    size_ratio = max(sizes) / min(sizes)
ValueError: max() arg is an empty sequence
```
And after adding a null check there I got the error

```
(conda_env_opt) [~/fbopt/metaseq]$ metaseq-api-local
2022-05-03 16:24:14 | INFO | metaseq_cli.interactive | Local checkpoint copy already exists, skipping copy
2022-05-03 16:24:15 | INFO | metaseq.tasks.language_modeling | dictionary: 50272 types
2022-05-03 16:24:15 | INFO | metaseq.hub_utils | loading model(s) from /home/jliu/fbopt/storage/175B/reshard_no_os/reshard.pt
got exception while trying to load /home/jliu/fbopt/storage/175B/reshard_no_os/reshard.pt with paths to load ['/home/jliu/fbopt/storage/175B/reshard_no_os/reshard.pt']
2022-05-03 16:24:15 | INFO | metaseq.checkpoint_utils | Done reading from disk
Traceback (most recent call last):
  File "/home/jliu/miniconda3/envs/conda_env_opt/bin/metaseq-api-local", line 33, in <module>
    sys.exit(load_entry_point('metaseq', 'console_scripts', 'metaseq-api-local')())
  File "/home/jliu/fbopt/metaseq/metaseq_cli/interactive_hosted.py", line 300, in cli_main
    dist_utils.call_main(cfg, worker_main, namespace_args=args)
  File "/home/jliu/fbopt/metaseq/metaseq/distributed/utils.py", line 226, in call_main
    main(cfg, **kwargs)
  File "/home/jliu/fbopt/metaseq/metaseq_cli/interactive_hosted.py", line 156, in worker_main
    models = generator.load_model()  # noqa: F841
  File "/home/jliu/fbopt/metaseq/metaseq/hub_utils.py", line 485, in load_model
    models, _model_args, _task = checkpoint_utils.load_model_ensemble_and_task(
  File "/home/jliu/fbopt/metaseq/metaseq/checkpoint_utils.py", line 475, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/jliu/fbopt/metaseq/metaseq/checkpoint_utils.py", line 425, in load_checkpoint_to_cpu
    if "cfg" in state and state["cfg"] is not None:
UnboundLocalError: local variable 'state' referenced before assignment
```

Not sure if I'm going in the right direction here though.

**Comment by jminjie** [comment]
Thanks Hunter! The sense I'm getting is that
1. I didn't download the weights and need to do that (https://github.com/facebookresearch/metaseq/tree/main/projects/OPT)
2. I'll try the changes in dict.txt and /assets and check back in.

Hopefully this will resolve the issues.

**Comment by jminjie** [comment]
After downloaded weights (for a smaller model) and the dict, I'm seeing
```
(conda_env_opt) [~/fbopt/storage]$ metaseq-api-local   
2022-05-03 16:40:45 | INFO | metaseq_cli.interactive | Local checkpoint copy already exists, skipping copy                                                                                                                    2022-05-03 16:40:45 | INFO | metaseq.tasks.language_modeling | dictionary: 50272 types                                                                                                                                        2022-05-03 16:40:45 | INFO | metaseq.hub_utils | loading model(s) from /home/jliu/fbopt/storage/175B/reshard_no_os/reshard.pt                                                                                                 2022-05-03 16:40:46 | INFO | metaseq.checkpoint_utils | Done reading from disk                                                                                                                                                Detected CUDA files, patching ldflags                                                                                                                                                                                         Emitting ninja build file /home/jliu/fbopt/Megatron-LM/megatron/fused_kernels/build/build.ninja...                                                                                                                            Building extension module scaled_upper_triang_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)                                                                                                             [1/3] c++ -MMD -MF scaled_upper_triang_masked_softmax.o.d -DTORCH_EXTENSION_NAME=scaled_upper_triang_masked_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -D
PYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/tor
ch/csrc/api/include -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/TH -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/THC -isystem /u
sr/local/cuda-11.3/include -isystem /home/jliu/miniconda3/envs/conda_env_opt/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -c /home/jliu/fbopt/Megatron-LM/megatron/fused_kernels/scaled_upper_triang_mask
ed_softmax.cpp -o scaled_upper_triang_masked_softmax.o     
[2/3] /usr/local/cuda-11.3/bin/nvcc  -DTORCH_EXTENSION_NAME=scaled_upper_triang_masked_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"
_cxxabi1011\" -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/TH -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda-11.3/include -isystem /home/jliu/miniconda3/envs/conda_env_opt/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -U__CUDA_NO_HALF_OPERATORS__ -U__
CUDA_NO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_80,code=sm_80 -std=c++14 -c /home/jliu/fbopt/Megatron-LM/megatron/fused_kernels/scaled_upper_triang_masked_softmax_cuda.cu -o scaled_upper_triang_masked_softmax_cuda.cuda.o                                                                                                                                                                               [3/3] c++ scaled_upper_triang_masked_softmax.o scaled_upper_triang_masked_softmax_cuda.cuda.o -shared -L/home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/usr/local/cuda-11.3/lib64 -lcudart -o scaled_upper_triang_masked_softmax_cuda.so                                                                                             Loading extension module scaled_upper_triang_masked_softmax_cuda...                                                                                                                                                           Detected CUDA files, patching ldflags                                                                                                                                                                                         
Emitting ninja build file /home/jliu/fbopt/Megatron-LM/megatron/fused_kernels/build/build.ninja...                                                                                                                            Building extension module scaled_masked_softmax_cuda...                             
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] c++ -MMD -MF scaled_masked_softmax.o.d -DTORCH_EXTENSION_NAME=scaled_masked_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxa
bi1011\" -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isyst
em /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/TH -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda-11.3/include
 -isystem /home/jliu/miniconda3/envs/conda_env_opt/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -c /home/jliu/fbopt/Megatron-LM/megatron/fused_kernels/scaled_masked_softmax.cpp -o scaled_masked_softmax
.o                                                                                                             
[2/3] /usr/local/cuda-11.3/bin/nvcc  -DTORCH_EXTENSION_NAME=scaled_masked_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\"
 -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home
/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/TH -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda-11.3/include -isyste
m /home/jliu/miniconda3/envs/conda_env_opt/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-re
laxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_
CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_80,code=sm_80 -std=c++14 -c /home/jliu/fbopt/Megatron-LM/megatron/fused_kernels/scaled_masked_softmax_cuda.cu -o scaled_masked_softmax_cud
a.cuda.o                                                                                                       
[3/3] c++ scaled_masked_softmax.o scaled_masked_softmax_cuda.cuda.o -shared -L/home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -lt
orch -ltorch_python -L/usr/local/cuda-11.3/lib64 -lcudart -o scaled_masked_softmax_cuda.so
Loading extension module scaled_masked_softmax_cuda...
Detected CUDA files, patching ldflags                                                                          
Emitting ninja build file /home/jliu/fbopt/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module fused_mix_prec_layer_norm_cuda...                          
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] c++ -MMD -MF layer_norm_cuda.o.d -DTORCH_EXTENSION_NAME=fused_mix_prec_layer_norm_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi
1011\" -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem
 /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/TH -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda-11.3/include -
isystem /home/jliu/miniconda3/envs/conda_env_opt/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -c /home/jliu/fbopt/Megatron-LM/megatron/fused_kernels/layer_norm_cuda.cpp -o layer_norm_cuda.o 
[2/3] /usr/local/cuda-11.3/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_mix_prec_layer_norm_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi10
11\" -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /
home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/TH -isystem /home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda-11.3/include -is
ystem /home/jliu/miniconda3/envs/conda_env_opt/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --exp
t-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -maxrregcount=50 -gencode arch=compute_80,
code=sm_80 -std=c++14 -c /home/jliu/fbopt/Megatron-LM/megatron/fused_kernels/layer_norm_cuda_kernel.cu -o layer_norm_cuda_kernel.cuda.o 
[3/3] c++ layer_norm_cuda.o layer_norm_cuda_kernel.cuda.o -shared -L/home/jliu/miniconda3/envs/conda_env_opt/lib/python3.9/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltor
ch_python -L/usr/local/cuda-11.3/lib64 -lcudart -o fused_mix_prec_layer_norm_cuda.so
Loading extension module fused_mix_prec_layer_norm_cuda...
Traceback (most recent call last):
  File "/home/jliu/miniconda3/envs/conda_env_opt/bin/metaseq-api-local", line 33, in <module>
    sys.exit(load_entry_point('metaseq', 'console_scripts', 'metaseq-api-local')())
  File "/home/jliu/fbopt/metaseq/metaseq_cli/interactive_hosted.py", line 300, in cli_main
    dist_utils.call_main(cfg, worker_main, namespace_args=args)
  File "/home/jliu/fbopt/metaseq/metaseq/distributed/utils.py", line 226, in call_main
    main(cfg, **kwargs)                                
  File "/home/jliu/fbopt/metaseq/metaseq_cli/interactive_hosted.py", line 156, in worker_main
    models = generator.load_model()  # noqa: F841
  File "/home/jliu/fbopt/metaseq/metaseq/hub_utils.py", line 485, in load_model
    models, _model_args, _task = checkpoint_utils.load_model_ensemble_and_task(
  File "/home/jliu/fbopt/metaseq/metaseq/checkpoint_utils.py", line 505, in load_model_ensemble_and_task
    model = build_model_hook(cfg, task)
  File "/home/jliu/fbopt/metaseq/metaseq/hub_utils.py", line 476, in _build_model
    return fsdp_wrap(model)
  File "/home/jliu/fbopt/metaseq/metaseq/distributed/fully_sharded_data_parallel.py", line 145, in fsdp_wrap
    return wrap(module, **kwargs)
  File "/home/jliu/fbopt/fairscale/fairscale/nn/wrap/auto_wrap.py", line 170, in wrap
    return ConfigAutoWrap.wrapper_cls(module, **wrap_overrides)
  File "/home/jliu/fbopt/metaseq/metaseq/distributed/fully_sharded_data_parallel.py", line 48, in __init__
    super().__init__(*args, **kwargs)
  File "/home/jliu/fbopt/fairscale/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 281, in __init__
    self.process_group = process_group or get_process_group_cached()
  File "/home/jliu/fbopt/fairscale/fairscale/utils/parallel.py", line 92, in get_process_group_cached
    raise RuntimeError("torch.distributed is not yet initialized but process group is requested.")
RuntimeError: torch.distributed is not yet initialized but process group is requested.
```

Any guidance here?

**Comment by stephenroller** [comment]
Can you report your fairscale version?

**Comment by jminjie** [comment]
I installed fairscale from source with 
```
git clone https://github.com/facebookresearch/fairscale.git
cd fairscale
git checkout prefetch_fsdp_params_simple
pip3 install -e .
```
as described in setup.md. I'm not sure how to check the version number. Based on fairscale/CHANGELOG.md it seems version 0.4.1 is the most recent version upgrade on this commit.

**Comment by DGideas** [comment]
> I installed fairscale from source with
> 
> ```
> git clone https://github.com/facebookresearch/fairscale.git
> cd fairscale
> git checkout prefetch_fsdp_params_simple
> pip3 install -e .
> ```
> 
> as described in setup.md. I'm not sure how to check the version number. Based on fairscale/CHANGELOG.md it seems version 0.4.1 is the most recent version upgrade on this commit.

I occurred this problems too. You could goto `fairscale/fairscale/__init__.py` and should noticed that `__version__ = "0.4.1"` on line 7

**Comment by seelam** [comment]
I still the issue, any resolution?

**Comment by stephenroller** [comment]
Which model are you using? How exactly have you set all the parameters?

This looks like distributed is not being initialized which is most strange.

**Comment by jminjie** [comment]
I really just followed your setup document, so the model and parameters are somewhat opaque to me. Can you recommend what files to check to give you the information you need?

**Comment by samuelstevens** [comment]
I am experiencing the same issue on commit 809e49cf. I have changed the MODEL_SHARED_FOLDER, LOCAL_SSD, CHECKPOINT_FOLDER, and CHECKPOINT_LOCAL variables in metaseq/service/constants.py.

I'm running it with `CUDA_HOME=/usr/local/cuda-11.6 metaseq-api-local`. 

I get `RuntimeError: torch.distributed is not yet initialized but process group is requested.` (same stack trace, fairseq version 0.4.1).

Maybe it is a cuda11.6 issue since metaseq uses 11.3?

**Comment by jminjie** [comment]
> Maybe it is a cuda11.6 issue since metaseq uses 11.3?

I'm using CUDA 11.3 and seeing the same error.

**Comment by RohitNagraj** [comment]
So from some research I did about torch.distributed, I found a way to get past this issue by making the following changes:
In `metaseq/distributed/utils.py`, between line 296 and 297, add the following code:

```
if not torch.distributed.is_initialized():
        os.environ['MASTER_ADDR'] = 'localhost'
        os.environ['MASTER_PORT'] = '12355'
        dist.init_process_group("nccl", rank=0, world_size=1)
```

This initializes torch.distributed. However, I also faced issues where the code crashed sometimes due to some cuda errors, which I did not pay a lot of attention to as restarting the server just fixed it.

I am not very familiar with torch.distributed and found this solution only by Googling. So there might be better ways to fix this.

**Comment by ForgetThatNight** [comment]
have you resolved it? I got same error too

**Comment by DGideas** [comment]
> have you resolved it? I got same error too

Do you want to fune-turing this model or just run it? If you want to run it, you could use OPT on HuggingFace(transformers), this method will bypasses these issues.

**Comment by stevenkwong** [comment]
> This is so strange. Can anyone provide the command they are running?

I met the same problem of "RuntimeError: torch.distributed is not yet initialized but process group is requested";
I just follow the official [setup instruction](https://github.com/facebookresearch/metaseq/blob/main/docs/setup.md), but install Apex in the end.
After finishing all instruction, I run “metaseq-api-local” ，then come up with this [error](https://github.com/facebookresearch/metaseq/issues/23#issuecomment-1116766593)

**Comment by yuvalkirstain** [comment]
@jminjie 
Regarding the exception:
```bash
RuntimeError: torch.distributed is not yet initialized but process group is requested.
```
what is the distributed world size you set? If it is 1, then this behavior is expected.
