### ISSUE TITLE
Convert to singleton script fails for 1.3B checkpoint

### ISSUE THREAD

**Issue by punitkoura** [facebookresearch/metaseq#233]
## 🐛 Bug

The convert_to_singleton.py script fails for the 1.3B checkpoint

### To Reproduce

```
ls 1.3b/
dict.txt  gpt2-merges.txt  gpt2-vocab.json  reshard-model_part-0.pt  reshard-model_part-1.pt
```
```
Loading extension module fused_mix_prec_layer_norm_cuda...
2022-07-19 03:15:10 | INFO | metaseq.modules.fused_bias_gelu | Done with compiling and loading fused kernels.
Traceback (most recent call last):
  File "/shared/home/punitkoura/miniconda3/envs/fairseq-20220503/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/shared/home/punitkoura/miniconda3/envs/fairseq-20220503/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/shared/home/punitkoura/src/metaseq/metaseq/scripts/convert_to_singleton.py", line 168, in <module>
    main()
  File "/shared/home/punitkoura/src/metaseq/metaseq/scripts/convert_to_singleton.py", line 164, in main
    dist_utils.call_main(cfg, worker_main)
  File "/shared/home/punitkoura/src/metaseq/metaseq/distributed/utils.py", line 263, in call_main
    return _spawn_helper(main, cfg, kwargs)
  File "/shared/home/punitkoura/src/metaseq/metaseq/distributed/utils.py", line 241, in _spawn_helper
    retval = distributed_main(-1, main, cfg, kwargs)
  File "/shared/home/punitkoura/src/metaseq/metaseq/distributed/utils.py", line 203, in distributed_main
    main(cfg, **kwargs)
  File "/shared/home/punitkoura/src/metaseq/metaseq/scripts/convert_to_singleton.py", line 113, in worker_main
    models, _model_args, _task = checkpoint_utils.load_model_ensemble_and_task(
  File "/shared/home/punitkoura/src/metaseq/metaseq/checkpoint_utils.py", line 582, in load_model_ensemble_and_task
    model = build_model_hook(cfg, task)
  File "/shared/home/punitkoura/src/metaseq/metaseq/scripts/convert_to_singleton.py", line 106, in _build_model
    model = task.build_model(cfg.model).half().cuda()
  File "/shared/home/punitkoura/src/metaseq/metaseq/tasks/base_task.py", line 551, in build_model
    model = models.build_model(args, self)
  File "/shared/home/punitkoura/src/metaseq/metaseq/models/__init__.py", line 89, in build_model
    return model.build_model(cfg, task)
  File "/shared/home/punitkoura/src/metaseq/metaseq/model_parallel/models/transformer_lm.py", line 55, in build_model
    decoder = ModelParallelTransformerDecoder(
  File "/shared/home/punitkoura/src/metaseq/metaseq/models/transformer.py", line 395, in __init__
    self.build_decoder_layer(
  File "/shared/home/punitkoura/src/metaseq/metaseq/models/transformer.py", line 542, in build_decoder_layer
    layer = fsdp_wrap(
  File "/shared/home/punitkoura/src/metaseq/metaseq/distributed/fully_sharded_data_parallel.py", line 145, in fsdp_wrap
    return wrap(module, **kwargs)
  File "/shared/home/punitkoura/src/fairscale/fairscale/nn/wrap/auto_wrap.py", line 187, in wrap
    return ConfigAutoWrap.wrapper_cls(module, **wrap_overrides)
  File "/shared/home/punitkoura/src/metaseq/metaseq/distributed/fully_sharded_data_parallel.py", line 48, in __init__
    super().__init__(*args, **kwargs)
  File "/shared/home/punitkoura/src/fairscale/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 459, in __init__
    self._fsdp_wrapped_module: nn.Module = FlattenParamsWrapper(
  File "/shared/home/punitkoura/src/fairscale/fairscale/nn/misc/flatten_params_wrapper.py", line 222, in __init__
    params, param_infos, shared_param_infos = self._init_flatten_params(new_p_set)
  File "/shared/home/punitkoura/src/fairscale/fairscale/nn/misc/flatten_params_wrapper.py", line 301, in _init_flatten_params
    assert (
AssertionError: expects all parameters to have same dtype: fp32: _fpw_module.self_attn_layer_norm,_fpw_module.self_attn_layer_norm,_fpw_module.final_layer_norm,_fpw_module.final_layer_norm 
 fp16: _fpw_module.self_attn.qkv_proj,_fpw_module.self_attn.qkv_proj,_fpw_module.self_attn.out_proj,_fpw_module.self_attn.out_proj,_fpw_module.fc1,_fpw_module.fc1,_fpw_module.fc2,_fpw_module.fc2 
```

### Expected behavior

We should get a consolidated 1.3B checkpoint.

### Environment

 - metaseq Version : main
 - PyTorch Version (e.g., 1.0) : 10
 - OS (e.g., Linux, Windows, MacOS):
 - How you installed metaseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by punitkoura** [comment]
Loading the model directly in pytorch shows that the model weights are all fp16

```
>>> model_part_0['model']
{'flat_param_0': tensor([ 0.0175, -0.0312, -0.0176,  ...,  0.0628,  0.0627, -0.1261],
       dtype=torch.float16), 'decoder.layers.0.flat_param_0': tensor([-0.0077,  0.0006, -0.0047,  ...,  0.1294, -0.0980,  0.1748],
       dtype=torch.float16), 'decoder.layers.1.flat_param_0': tensor([-0.0054, -0.0271,  0.0388,  ...,  0.0335, -0.0989,  0.0435],
       dtype=torch.float16), 'decoder.layers.2.flat_param_0': tensor([ 0.0003, -0.0127, -0.0196,  ...,  0.0460, -0.0118,  0.0234],
       dtype=torch.float16), 'decoder.layers.3.flat_param_0': tensor([-0.0107, -0.0008, -0.0078,  ...,  0.0984,  0.0178,  0.0952],
       dtype=torch.float16), 'decoder.layers.4.flat_param_0': tensor([-0.0056,  0.0081,  0.0091,  ...,  0.0941,  0.0424,  0.1259],
       dtype=torch.float16), 'decoder.layers.5.flat_param_0': tensor([-0.0382, -0.0464,  0.0257,  ...,  0.1022, -0.0493,  0.1467],
       dtype=torch.float16), 'decoder.layers.6.flat_param_0': tensor([-0.0288,  0.0699, -0.0195,  ...,  0.0900, -0.0624,  0.1768],
       dtype=torch.float16), 'decoder.layers.7.flat_param_0': tensor([ 0.0107, -0.0251,  0.0219,  ...,  0.0466,  0.0356,  0.1627],
       dtype=torch.float16), 'decoder.layers.8.flat_param_0': tensor([-5.8479e-03, -1.0490e-04,  2.7451e-02,  ...,  3.0228e-02,
         4.2328e-02,  1.4246e-01], dtype=torch.float16), 'decoder.layers.9.flat_param_0': tensor([ 0.0230, -0.0196, -0.0193,  ...,  0.0696,  0.0743,  0.1597],
       dtype=torch.float16), 'decoder.layers.10.flat_param_0': tensor([ 0.0173, -0.0018,  0.0021,  ...,  0.0741,  0.0785,  0.1088],
       dtype=torch.float16), 'decoder.layers.11.flat_param_0': tensor([ 0.0023, -0.0336, -0.0423,  ...,  0.0460,  0.0654,  0.0141],
       dtype=torch.float16), 'decoder.layers.12.flat_param_0': tensor([ 0.0109,  0.0324, -0.0252,  ...,  0.0526,  0.1113,  0.0756],
       dtype=torch.float16), 'decoder.layers.13.flat_param_0': tensor([-0.0019,  0.0066,  0.0494,  ...,  0.0966,  0.0963,  0.0832],
       dtype=torch.float16), 'decoder.layers.14.flat_param_0': tensor([ 0.0084,  0.0071, -0.0066,  ...,  0.1041,  0.0629,  0.0935],
       dtype=torch.float16), 'decoder.layers.15.flat_param_0': tensor([-0.0120, -0.0179,  0.0095,  ...,  0.0956,  0.0532,  0.0698],
       dtype=torch.float16), 'decoder.layers.16.flat_param_0': tensor([0.0380, 0.0175, 0.0771,  ..., 0.0677, 0.0836, 0.1102],
       dtype=torch.float16), 'decoder.layers.17.flat_param_0': tensor([ 0.0127, -0.0021, -0.0354,  ...,  0.0746,  0.0457,  0.1041],
       dtype=torch.float16), 'decoder.layers.18.flat_param_0': tensor([ 0.0043, -0.0098,  0.0331,  ...,  0.0395,  0.0297,  0.1556],
       dtype=torch.float16), 'decoder.layers.19.flat_param_0': tensor([ 0.0160,  0.0120, -0.0135,  ...,  0.0754,  0.0518,  0.1599],
       dtype=torch.float16), 'decoder.layers.20.flat_param_0': tensor([ 0.0107, -0.0221, -0.0290,  ...,  0.0074,  0.0284,  0.1565],
       dtype=torch.float16), 'decoder.layers.21.flat_param_0': tensor([ 0.0022,  0.0184,  0.0092,  ..., -0.0153,  0.0534,  0.1417],
       dtype=torch.float16), 'decoder.layers.22.flat_param_0': tensor([-0.0038,  0.0033,  0.0004,  ...,  0.0483,  0.1243,  0.1455],
       dtype=torch.float16), 'decoder.layers.23.flat_param_0': tensor([0.0280, 0.0198, 0.0012,  ..., 0.0743, 0.1257, 0.1272],
       dtype=torch.float16), 'decoder.version': tensor([3.], dtype=torch.float16)}
>>> model_part_1['model']
{'flat_param_0': tensor([-0.0101, -0.0555, -0.0057,  ...,  0.0628,  0.0627, -0.1261],
       dtype=torch.float16), 'decoder.layers.0.flat_param_0': tensor([-0.0193, -0.0059,  0.0023,  ...,  0.1294, -0.0980,  0.1748],
       dtype=torch.float16), 'decoder.layers.1.flat_param_0': tensor([-0.0224, -0.0119,  0.0501,  ...,  0.0335, -0.0989,  0.0435],
       dtype=torch.float16), 'decoder.layers.2.flat_param_0': tensor([-0.0188,  0.0075, -0.0233,  ...,  0.0460, -0.0118,  0.0234],
       dtype=torch.float16), 'decoder.layers.3.flat_param_0': tensor([ 0.0148,  0.0152, -0.0469,  ...,  0.0984,  0.0178,  0.0952],
       dtype=torch.float16), 'decoder.layers.4.flat_param_0': tensor([-0.0157,  0.0191,  0.0010,  ...,  0.0941,  0.0424,  0.1259],
       dtype=torch.float16), 'decoder.layers.5.flat_param_0': tensor([ 0.0242,  0.0109,  0.0105,  ...,  0.1022, -0.0493,  0.1467],
       dtype=torch.float16), 'decoder.layers.6.flat_param_0': tensor([ 0.0198, -0.0174,  0.0019,  ...,  0.0900, -0.0624,  0.1768],
       dtype=torch.float16), 'decoder.layers.7.flat_param_0': tensor([-0.0004,  0.0111,  0.0102,  ...,  0.0466,  0.0356,  0.1627],
       dtype=torch.float16), 'decoder.layers.8.flat_param_0': tensor([-0.0067, -0.0187,  0.0214,  ...,  0.0302,  0.0423,  0.1425],
       dtype=torch.float16), 'decoder.layers.9.flat_param_0': tensor([0.0210, 0.0256, 0.0497,  ..., 0.0696, 0.0743, 0.1597],
       dtype=torch.float16), 'decoder.layers.10.flat_param_0': tensor([-0.0030, -0.0086,  0.0446,  ...,  0.0741,  0.0785,  0.1088],
       dtype=torch.float16), 'decoder.layers.11.flat_param_0': tensor([-0.0477,  0.0024, -0.0615,  ...,  0.0460,  0.0654,  0.0141],
       dtype=torch.float16), 'decoder.layers.12.flat_param_0': tensor([-0.0078,  0.0558, -0.0541,  ...,  0.0526,  0.1113,  0.0756],
       dtype=torch.float16), 'decoder.layers.13.flat_param_0': tensor([-0.0019, -0.0013,  0.0115,  ...,  0.0966,  0.0963,  0.0832],
       dtype=torch.float16), 'decoder.layers.14.flat_param_0': tensor([ 0.0168, -0.0008, -0.0090,  ...,  0.1041,  0.0629,  0.0935],
       dtype=torch.float16), 'decoder.layers.15.flat_param_0': tensor([ 0.0013, -0.0101,  0.0301,  ...,  0.0956,  0.0532,  0.0698],
       dtype=torch.float16), 'decoder.layers.16.flat_param_0': tensor([0.0151, 0.0016, 0.0128,  ..., 0.0677, 0.0836, 0.1102],
       dtype=torch.float16), 'decoder.layers.17.flat_param_0': tensor([-0.0057,  0.0384, -0.0009,  ...,  0.0746,  0.0457,  0.1041],
       dtype=torch.float16), 'decoder.layers.18.flat_param_0': tensor([0.0107, 0.0131, 0.0483,  ..., 0.0395, 0.0297, 0.1556],
       dtype=torch.float16), 'decoder.layers.19.flat_param_0': tensor([0.0193, 0.0009, 0.0134,  ..., 0.0754, 0.0518, 0.1599],
       dtype=torch.float16), 'decoder.layers.20.flat_param_0': tensor([-0.0103, -0.0091,  0.0078,  ...,  0.0074,  0.0284,  0.1565],
       dtype=torch.float16), 'decoder.layers.21.flat_param_0': tensor([-0.0376,  0.0095,  0.0466,  ..., -0.0153,  0.0534,  0.1417],
       dtype=torch.float16), 'decoder.layers.22.flat_param_0': tensor([-0.0007, -0.0085,  0.0055,  ...,  0.0483,  0.1243,  0.1455],
       dtype=torch.float16), 'decoder.layers.23.flat_param_0': tensor([-0.0407, -0.0245,  0.0445,  ...,  0.0743,  0.1257,  0.1272],
       dtype=torch.float16), 'decoder.version': tensor([3.], dtype=torch.float16)}
>>> 
```

**Comment by punitkoura** [comment]
Adding this change 
```
--- a/metaseq/scripts/convert_to_singleton.py
+++ b/metaseq/scripts/convert_to_singleton.py
@@ -103,6 +103,8 @@ def worker_main(cfg: MetaseqConfig):
 
     def _build_model(cfg, task):
         # hardcoded to cpu & fp16
+        # Hardcoded tensor_parallel_init_model_on_gpu to be True
+        cfg.model.tensor_parallel_init_model_on_gpu = True
         model = task.build_model(cfg.model).half().cuda()
         return fsdp_wrap(model)

```

makes the script work. This is because the layer norm layers are created when we initialize the model, and by default they are initialized as fp32. Unless the tensor_parallel_init_model_on_gpu is passed, the layer norm layers are not converted to fp16, hence causing the discrepancy.
