### ISSUE TITLE
World size mismatch for convert_to_singleton.py

### ISSUE THREAD

**Issue by EIFY** [facebookresearch/metaseq#378]
#### What is your question?
Maybe I am missing something obvious, but I got the following error when I tried to run `convert_to_singleton.py`:
```
$ ls 1.3b/
dict.txt  gpt2-merges.txt  gpt2-vocab.json  reshard-model_part-0.pt  reshard-model_part-1.pt
$ python -m metaseq.scripts.convert_to_singleton 1.3b/
['--model-parallel-size', '2', '--distributed-world-size', '2', '--task', 'language_modeling', '--bpe-merges', '1.3b//gpt2-merges.txt', '--merges-filename', '1.3b//gpt2-merges.txt', '--bpe-vocab', '1.3b//gpt2-vocab.json', '--vocab-filename', '1.3b//gpt2-vocab.json', '--bpe', 'hf_byte_bpe', '--path', '1.3b//reshard.pt', '--checkpoint-shard-count', '1', '--use-sharded-state', '1.3b/']
Traceback (most recent call last):
  File "/home/jason_chou/.conda/envs/user/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jason_chou/.conda/envs/user/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jason_chou/metaseq/metaseq/scripts/convert_to_singleton.py", line 168, in <module>
    main()
  File "/home/jason_chou/metaseq/metaseq/scripts/convert_to_singleton.py", line 164, in main
    distributed_utils.call_main(cfg, worker_main)
  File "/home/jason_chou/metaseq/metaseq/distributed/utils.py", line 264, in call_main
    infer_init_method(cfg.distributed_training)
  File "/home/jason_chou/metaseq/metaseq/distributed/utils.py", line 53, in infer_init_method
    _infer_single_node_init(cfg)
  File "/home/jason_chou/metaseq/metaseq/distributed/utils.py", line 115, in _infer_single_node_init
    ), f"world size is {cfg.distributed_world_size} but have {torch.cuda.device_count()} available devices"
AssertionError: world size is 2 but have 1 available devices
```
Does the number of GPUs needs to match the number of sharded files? Alternatively, is there an easier way to load a sharded model? I have set the following in my `constants.py` but it has no effect (as expected)
```
MODEL_PARALLEL = 1
TOTAL_WORLD_SIZE = 1
```
#### What have you tried?
As a long shot I have also tried hacking `convert_to_singleton.py`
```
def create_generation_config_with_defaults(model_path):
    files = glob.glob(f"{model_path}/reshard*.pt")

    MP = 1 # len(files)
    BPE_MERGES = model_path + "/gpt2-merges.txt"
    BPE_VOCAB = model_path + "/gpt2-vocab.json"
    (...)
```
But it still didn't work, more or less as expected:
```
$ python -m metaseq.scripts.convert_to_singleton 1.3b/
['--model-parallel-size', '1', '--distributed-world-size', '1', '--task', 'language_modeling', '--bpe-merges', '1.3b//gpt2-merges.txt', '--merges-filename', '1.3b//gpt2-merges.txt', '--bpe-vocab', '1.3b//gpt2-vocab.json', '--vocab-filename', '1.3b//gpt2-vocab.json', '--bpe', 'hf_byte_bpe', '--path', '1.3b//reshard.pt', '--checkpoint-shard-count', '1', '--use-sharded-state', '1.3b/']
Traceback (most recent call last):
  File "/home/jason_chou/.conda/envs/user/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jason_chou/.conda/envs/user/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jason_chou/metaseq/metaseq/scripts/convert_to_singleton.py", line 168, in <module>
    main()
  File "/home/jason_chou/metaseq/metaseq/scripts/convert_to_singleton.py", line 164, in main
    distributed_utils.call_main(cfg, worker_main)
  File "/home/jason_chou/metaseq/metaseq/distributed/utils.py", line 279, in call_main
    return main(cfg, **kwargs)
  File "/home/jason_chou/metaseq/metaseq/scripts/convert_to_singleton.py", line 120, in worker_main
    build_model_hook=_build_model,
  File "/home/jason_chou/metaseq/metaseq/checkpoint_utils.py", line 448, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/jason_chou/metaseq/metaseq/checkpoint_utils.py", line 383, in load_checkpoint_to_cpu
    paths_to_load = get_paths_to_load(local_path, suffix="shard")
  File "/home/jason_chou/metaseq/metaseq/checkpoint_utils.py", line 323, in get_paths_to_load
    if not _is_checkpoint_sharded(checkpoint_files):
  File "/home/jason_chou/metaseq/metaseq/checkpoint_utils.py", line 314, in _is_checkpoint_sharded
    size_ratio = max(sizes) / min(sizes)
ValueError: max() arg is an empty sequence
```

#### What's your environment?

 - metaseq Version (e.g., 1.0 or master): HEAD detached at 493e601, due to my python version
 - PyTorch Version (e.g., 1.0): 1.10.1+cu113
 - OS (e.g., Linux): Ubuntu 18.04.6 LTS
 - How you installed metaseq (`pip`, source): `pip`
 - Build command you used (if compiling from source): N.A.
 - Python version: 3.7.13
 - CUDA/cuDNN version: CUDA 11.7
 - GPU models and configuration: 1 x T4

**Comment by suchenzang** [comment]
@tangbinh this might be something to keep in mind while you're tackling https://github.com/facebookresearch/metaseq/issues/376

**Comment by tangbinh** [comment]
@EIFY My apologies for the late response.
> Does the number of GPUs needs to match the number of sharded files?

Indeed, this is the case with the script [convert_to_singleton.py](https://github.com/facebookresearch/metaseq/blob/071b17aad97e7257cc026cf5d03492520bec5b91/metaseq/scripts/convert_to_singleton.py) because it relies on DDP processes. There are other scripts in the repo that convert sharded checkpoints into one singleton on CPU (e.g. [consolidate_fsdp_shards.py](https://github.com/facebookresearch/metaseq/blob/071b17aad97e7257cc026cf5d03492520bec5b91/metaseq/scripts/consolidate_fsdp_shards.py), [reshard_model_parallel.py](https://github.com/facebookresearch/metaseq/blob/071b17aad97e7257cc026cf5d03492520bec5b91/metaseq/scripts/reshard_model_parallel.py)), so you might want to give them a try (there are some caveats, though). Please let me know if you need further help.

**Comment by EIFY** [comment]
@tangbinh Alright sounds reasonable. We are trying to load the sharded checkpoint directly at #407 🙃
