### ISSUE TITLE
"No package metadata was found for metaseq" when execute metaseq-api-local command

### ISSUE THREAD

**Issue by DGideas** [facebookresearch/metaseq#40]
#### What is your question?
I try to run metaseq-api using Google Colab, but when I execute metaseq-api-local command after setup, I got these error message:
```
Traceback (most recent call last):
  File "/usr/bin/metaseq-api-local", line 33, in <module>
    sys.exit(load_entry_point('metaseq', 'console_scripts', 'metaseq-api-local')())
  File "/usr/bin/metaseq-api-local", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 975, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 566, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for metaseq
```

I'm not sure if anyone else has a similar problem. Also, I'm using a different environment to try to see if I can reproduce this issue. However, Google Colab can reproduce this problem, see the code below:

#### Code

https://gist.github.com/DGideas/7c7147d7c965a477d977644806f0ca2a

#### What have you tried?
* Create a new Google Colab execution environment and retry
* I'm using a different environment to try to see if I can reproduce this issue

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0) 1.10.1
 - OS (e.g., Linux): Ubuntu 20.04 LTS / Linux
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source): see the code above
 - Python version: 3.8.10
 - CUDA/cuDNN version: 11.3
 - GPU models and configuration: Nvidia T40
 - Any other relevant information: n/a

**Comment by suchenzang** [comment]
Not too familiar with colab environment setup, though from a scan of your code it seems like you're cloning into each subsequent directory (starting from Megatron-LM -> fairscale -> metaseq) such that metaseq looks to be installed within Megatron-LM/fairscale/?  Is that intended / actually what's happening?

**Comment by DGideas** [comment]
> Not too familiar with colab environment setup, though from a scan of your code it seems like you're cloning into each subsequent directory (starting from Megatron-LM -> fairscale -> metaseq) such that metaseq looks to be installed within Megatron-LM/fairscale/? Is that intended / actually what's happening?

Thank you for your comment, I don't think it matters much. In each Colab code block, the working directory is automatically reset to `~/`. I'm still working on reproduce this issue on other cloud service provider server

**Comment by DGideas** [comment]
Update: I tried these init script on a Tencent Cloud 1*Nvidia T4 GPU VM, and got these error message: 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (MarkupSafe 1.1.0 (/usr/lib/python3/dist-packages), Requirement.parse('MarkupSafe>=2.0'), {'Jinja2'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/metaseq-api-local", line 33, in <module>
    sys.exit(load_entry_point('metaseq', 'console_scripts', 'metaseq-api-local')())
  File "/home/ubuntu/.local/bin/metaseq-api-local", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/fairscale/metaseq/metaseq_cli/interactive_hosted.py", line 16, in <module>
    import pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (MarkupSafe 1.1.0 (/usr/lib/python3/dist-packages), Requirement.parse('MarkupSafe>=2.0'), {'Jinja2'})
```

**Comment by stephenroller** [comment]
It feels like you're not doing "pip install -e ."

**Comment by DGideas** [comment]
I think I solved this problem, as @stephenroller said, the instruction `pip3 install -e .` doesn't work properly, I use:
```
!git clone https://github.com/facebookresearch/metaseq.git && cd metaseq && python3 setup.py install && pre-commit install
```
**python3 setup.py install** instead of `pip3 install -e .` to solve this problem!

**Comment by DGideas** [comment]
Thanks @suchenzang too!
