### ISSUE TITLE
`convert_to_singleton` TypeError: FullyShardedDataParallel.__init__() got an unexpected keyword argument 'process_group_reduce_scatter'

### ISSUE THREAD

**Issue by EIFY** [facebookresearch/metaseq#404]
## 🐛 Bug
With the directory prepared
```
$ ls 2.7b/
dict.txt  gpt2-merges.txt  gpt2-vocab.json  reshard-model_part-0.pt  reshard-model_part-1.pt  reshard-model_part-2.pt  reshard-model_part-3.pt
```
Running the following
```
NCCL_SHM_DISABLE=1 NCCL_DEBUG=INFO python -m metaseq.scripts.convert_to_singleton 2.7b/
```
ended up with the following:
```
2022-10-11 21:28:57 | INFO | metaseq.checkpoint_utils | Done reading from disk
Traceback (most recent call last):
  File "/home/jason_chou/.conda/envs/user/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jason_chou/.conda/envs/user/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jason_chou/metaseq/metaseq/scripts/convert_to_singleton.py", line 170, in <module>
    main()
  File "/home/jason_chou/metaseq/metaseq/scripts/convert_to_singleton.py", line 166, in main
    distributed_utils.call_main(cfg, worker_main)
  File "/home/jason_chou/metaseq/metaseq/distributed/utils.py", line 272, in call_main
    return _spawn_helper(main, cfg, kwargs)
  File "/home/jason_chou/metaseq/metaseq/distributed/utils.py", line 250, in _spawn_helper
    retval = distributed_main(-1, main, cfg, kwargs)
  File "/home/jason_chou/metaseq/metaseq/distributed/utils.py", line 212, in distributed_main
    retval = main(cfg, **kwargs)
  File "/home/jason_chou/metaseq/metaseq/scripts/convert_to_singleton.py", line 115, in worker_main
    models, _model_args, _task = checkpoint_utils.load_model_ensemble_and_task(
  File "/home/jason_chou/metaseq/metaseq/checkpoint_utils.py", line 482, in load_model_ensemble_and_task
    model = build_model_hook(cfg, task)
  File "/home/jason_chou/metaseq/metaseq/scripts/convert_to_singleton.py", line 108, in _build_model
    model = task.build_model(cfg.model).cuda()
  File "/home/jason_chou/metaseq/metaseq/tasks/base_task.py", line 531, in build_model
    model = models.build_model(args, self)
  File "/home/jason_chou/metaseq/metaseq/models/__init__.py", line 87, in build_model
    return model.build_model(cfg, task)
  File "/home/jason_chou/metaseq/metaseq/model_parallel/models/transformer_lm.py", line 55, in build_model
    decoder = ModelParallelTransformerDecoder(
  File "/home/jason_chou/metaseq/metaseq/models/transformer_decoder.py", line 129, in __init__
    layers.append(self.build_decoder_layer(args))
  File "/home/jason_chou/metaseq/metaseq/models/transformer_decoder.py", line 278, in build_decoder_layer
    layer = fsdp_wrap(
  File "/home/jason_chou/metaseq/metaseq/distributed/fully_sharded_data_parallel.py", line 146, in fsdp_wrap
    return wrap(module, **kwargs)
  File "/home/default_user/fairscale/fairscale/nn/wrap/auto_wrap.py", line 170, in wrap
    return ConfigAutoWrap.wrapper_cls(module, **wrap_overrides)
  File "/home/jason_chou/metaseq/metaseq/distributed/fully_sharded_data_parallel.py", line 48, in __init__
    super().__init__(*args, **kwargs)
TypeError: FullyShardedDataParallel.__init__() got an unexpected keyword argument 'process_group_reduce_scatter'
```
After grokking the codebase, I commented out the line that specifies `process_group_reduce_scatter`:
https://github.com/facebookresearch/metaseq/blob/51ab174b86ec0ca8d371211a16a7ff84266b6dfd/metaseq/distributed/fully_sharded_data_parallel.py#L107
Then it worked!
```
$ NCCL_SHM_DISABLE=1 NCCL_DEBUG=INFO python -m metaseq.scripts.convert_to_singleton 2.7b/
['--model-parallel-size', '4', '--distributed-world-size', '4', '--ddp-backend', 'pytorch_ddp', '--task', 'language_modeling', '--bpe-merges', '2.7b//gpt2-merges.txt', '--merges-filename', '2.7b//gpt2-merges.txt', '--bpe-vocab', '2.7b//gpt2-vocab.json', '--vocab-filename', '2.7b//gpt2-vocab.json', '--bpe', 'hf_byte_bpe', '--path', '2.7b//reshard.pt', '--checkpoint-shard-count', '1', '--use-sharded-state', '2.7b/']
(...)
2022-10-11 21:31:32 | INFO | metaseq.checkpoint_utils | Done reading from disk
$ ls 2.7b/
dict.txt  gpt2-merges.txt  gpt2-vocab.json  reshard-model_part-0.pt  reshard-model_part-1.pt  reshard-model_part-2.pt  reshard-model_part-3.pt  restored.pt
```
I am hesitant to just submit a 1-liner PR to do this because I am not sure if it's the right thing to do. The model loaded from the resulting `restored.pt` seems to behave reasonably though.

### To Reproduce
See above

### Expected behavior
`restored.pt` written out without such hacking
### Environment

 - metaseq Version : latest main 15ff28ef9108ff9dfe501213aaa3d5873728f217
 - PyTorch Version: 1.12.1+cu113
 - OS: Ubuntu 18.04.6 LTS
 - How you installed metaseq: `pip`
 - Build command you used (if compiling from source): N.A.
 - Python version: 3.10
 - CUDA/cuDNN version: CUDA 11.8
 - GPU models and configuration: 4 x T4

**Comment by EIFY** [comment]
Oh! This is the same issue as https://github.com/facebookresearch/metaseq/pull/349#issuecomment-1269519987, therefore already fixed in the setup instructions.
