### ISSUE TITLE
NFS async save gets "OSError: [Errno 14] Bad address", rename does not complete

### ISSUE THREAD

**Issue by suchenzang** [facebookresearch/metaseq#493]
When testing with 4 node (32 GPU) job with async write to NFS, we get the following error:

```
Traceback (most recent call last):
  File "/home/susanz/.conda/envs/metaseq-20221105/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self._pool.submit(func).result()  # Wait for job to finish.
  File "/home/susanz/.conda/envs/metaseq-20221105/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    self.run()
  File "/home/susanz/.conda/envs/metaseq-20221105/lib/python3.9/threading.py", line 917, in run
    return self.__get_result()
  File "/home/susanz/.conda/envs/metaseq-20221105/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    self._target(*self._args, **self._kwargs)
  File "/home/susanz/rsc/metaseq-internal/slurm_snapshot_code_oss/2022-11-05T20_18_51.243556/metaseq/file_io/common/non_blocking_io.py", line 142, in _poll_jobs
    raise self._exception
  File "/home/susanz/.conda/envs/metaseq-20221105/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    self._pool.submit(func).result()  # Wait for job to finish.
  File "/home/susanz/.conda/envs/metaseq-20221105/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/susanz/.conda/envs/metaseq-20221105/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    result = self.fn(*self.args, **self.kwargs)
  File "/home/susanz/rsc/metaseq-internal/slurm_snapshot_code_oss/2022-11-05T20_18_51.243556/metaseq/file_io/common/non_blocking_io.py", line 254, in <lambda>
    raise self._exception
  File "/home/susanz/.conda/envs/metaseq-20221105/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    self._notify_manager(lambda: self._io.write(b))
OSError: [Errno 14] Bad address
    result = self.fn(*self.args, **self.kwargs)
  File "/home/susanz/rsc/metaseq-internal/slurm_snapshot_code_oss/2022-11-05T20_18_51.243556/metaseq/file_io/common/non_blocking_io.py", line 254, in <lambda>
    self._notify_manager(lambda: self._io.write(b))
OSError: [Errno 14] Bad address
```

When looking at the checkpoint dir on NFS, the files remain in a directory prefixed with `_` (rename in https://github.com/facebookresearch/metaseq/blob/d46662cef7a21149b55b44f47442d4aefd6c3c23/metaseq/cli/train.py#L510-L516 does not complete), and `checkpoint-model_part-0-shard0.pt` is consistently missing.

When navigating to local scratch, we see:
```
(base) [susanz@<redacted>]$ ls -la
total 2930112
drwxrwsr-x 2 susanz susanz      4096 Nov  6 08:15 .
drwxr-sr-x 3 susanz susanz       230 Nov  6 08:14 ..
-rw-rw-r-- 1 susanz susanz        64 Nov  6 08:14 checkpoint_100-model_part-0-shard0.pt
-rw-rw-r-- 1 susanz susanz 214312775 Nov  6 08:14 checkpoint_100-model_part-1-shard0.pt
-rw-rw-r-- 1 susanz susanz 214312775 Nov  6 08:14 checkpoint_100-model_part-2-shard0.pt
-rw-rw-r-- 1 susanz susanz 214312775 Nov  6 08:14 checkpoint_100-model_part-3-shard0.pt
-rw-rw-r-- 1 susanz susanz 214312775 Nov  6 08:14 checkpoint_100-model_part-4-shard0.pt
-rw-rw-r-- 1 susanz susanz 214312775 Nov  6 08:14 checkpoint_100-model_part-5-shard0.pt
-rw-rw-r-- 1 susanz susanz 214312775 Nov  6 08:14 checkpoint_100-model_part-6-shard0.pt
-rw-rw-r-- 1 susanz susanz 214312775 Nov  6 08:14 checkpoint_100-model_part-7-shard0.pt
-rw-rw-r-- 1 susanz susanz        64 Nov  6 08:15 checkpoint_200-model_part-0-shard0.pt
-rw-rw-r-- 1 susanz susanz 214312775 Nov  6 08:15 checkpoint_200-model_part-1-shard0.pt
-rw-rw-r-- 1 susanz susanz 214312775 Nov  6 08:15 checkpoint_200-model_part-2-shard0.pt
-rw-rw-r-- 1 susanz susanz 214312775 Nov  6 08:15 checkpoint_200-model_part-3-shard0.pt
-rw-rw-r-- 1 susanz susanz 214312775 Nov  6 08:15 checkpoint_200-model_part-4-shard0.pt
-rw-rw-r-- 1 susanz susanz 214312775 Nov  6 08:15 checkpoint_200-model_part-5-shard0.pt
-rw-rw-r-- 1 susanz susanz 214312775 Nov  6 08:15 checkpoint_200-model_part-6-shard0.pt
-rw-rw-r-- 1 susanz susanz 214312775 Nov  6 08:15 checkpoint_200-model_part-7-shard0.pt
-rw-rw-r-- 1 susanz susanz     10838 Nov  6 08:14 config.yml
```
and on NFS we see:
```
(base) [susanz@<redacted> susan_test_17]$ ls
_checkpoint_100
_checkpoint_200
susan_test_17.bm_none.tok<redacted>
```

Job then hangs after a few failed checkpoint writes (5 minute timeout?) and requires manually cancelling.

-----

To confirm this is only an async write issue, I modified the async callback save from https://github.com/facebookresearch/metaseq/blob/d46662cef7a21149b55b44f47442d4aefd6c3c23/metaseq/checkpoint_utils.py#L605-L606
to:
```
with PathManager.open(filename, "wb") as f:
    _torch_persistent_save(obj, f)
async_callback_fn(filename)
```
which works as expected (checkpoints are saved to NFS properly, all shards are there, rename happens, etc.).

**Comment by suchenzang** [comment]
This looks like a potential issue with `PathManager.opena` logic; have instrumented https://github.com/facebookresearch/metaseq/pull/494/files as a workaround.

**Comment by suchenzang** [comment]
This error disappears when removing `PathManager.opena` logic.
