### ISSUE TITLE
Launch does not exit with --tombstonable

### ISSUE THREAD

**Issue by suchenzang** [facebookresearch/metaseq#508]
On job launch, we now hang until keyboard interrupting when `--tombstonable` is set:
```
...
 wait $!
 sleep 610 &
 wait $!'

Launched job 165793
Launched 165793

^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/susanz/.conda/envs/metaseq-20221105/lib/python3.9/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/susanz/.conda/envs/metaseq-20221105/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/susanz/.conda/envs/metaseq-20221105/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/susanz/rsc/metaseq-internal/metaseq_internal/fb_sweep/tombyard.py", line 104, in tombstones_procedure
    time.sleep(period.total_seconds())
KeyboardInterrupt
```

**Comment by igormolybogFB** [comment]
This was an intended behavior before my patch this morning: after launching the job, slurm.py starts the tombstoning process and holds the terminal for stdout. My most recent PR (https://github.com/fairinternal/metaseq-internal/pull/588) makes sure that the tombstoning is launched with nohup, so that the user gets their terminal back
