### ISSUE TITLE
Add kill-switch logic around time out errors

### ISSUE THREAD

**Issue by suchenzang** [facebookresearch/metaseq#52]
We are seeing cases where jobs will continue to stay alive after a series of

```
    raise RuntimeError(
RuntimeError: Timed out initializing process group in store based barrier on rank: 4330, for key: store_based_barrier_key:522 (world_size=2048, worker_count=1792, timeout=0:30:00)
```

errors when initializing the job. We should add logic to terminate these runs to free up resources.

**Comment by Mrs-Hudson** [comment]
Hi @suchenzang  I see this issue while trying to run metaseq_cli using the 350M model:
`2022-05-10 05:38:33 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:38:33 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:38:43 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:38:43 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:38:53 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:38:53 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:39:03 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:39:03 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:39:13 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:39:13 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:39:23 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:39:23 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:39:33 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:39:33 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/azureuser/metaseq/metaseq_cli/interactive_hosted.py", line 308, in <module>
    cli_main()
  File "/home/azureuser/metaseq/metaseq_cli/interactive_hosted.py", line 304, in cli_main
    dist_utils.call_main(cfg, worker_main, namespace_args=args)
  File "/home/azureuser/metaseq/metaseq/distributed/utils.py", line 256, in call_main
    return _spawn_helper(main, cfg, kwargs)
  File "/home/azureuser/metaseq/metaseq/distributed/utils.py", line 234, in _spawn_helper
    retval = distributed_main(-1, main, cfg, kwargs)
  File "/home/azureuser/metaseq/metaseq/distributed/utils.py", line 198, in distributed_main
    cfg.distributed_training.distributed_rank = distributed_init(cfg)
  File "/home/azureuser/metaseq/metaseq/distributed/utils.py", line 136, in distributed_init
    dist.init_process_group(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 608, in init_process_group
    _store_based_barrier(rank, store, timeout)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 244, in _store_based_barrier
    raise RuntimeError(
RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)`


Is there a workaround for this yet?

**Comment by suchenzang** [comment]
@Mrs-Hudson That looks to be a separate issue - not sure why your world_size (2) is less than your worker_count (3).   We see the above error when trying to run a 2k GPU job and there's underlying hardware issues (necessitating a kill-switch implementation to free up resources).

Please open a separate issue with information about your setup.

**Comment by Mrs-Hudson** [comment]
Thanks @suchenzang , opened #86

**Comment by stephenroller** [comment]
Closing this since I think the worker count was a bug from #79.

**Comment by suchenzang** [comment]
@stephenroller I don't think this is related to https://github.com/facebookresearch/metaseq/pull/79? This error came up from launching a training run with 2k GPUs in our internal compute env.

**Comment by suchenzang** [comment]
Watchdog timeout addresses the above for now
