### ISSUE TITLE
How to use OPT weights in metaseq-api-local API?

### ISSUE THREAD

**Issue by upwindflys** [facebookresearch/metaseq#610]
## ❓ How to use OPT weights in metaseq-api-local API?
I download pt files from the link https://github.com/facebookresearch/metaseq/tree/main/projects/OPT,
and the downloaded dir ```/root/data/OPT/1.3b/ ``` contains 2 files,
```reshard-model_part-0.pt   reshard-model_part-1.pt```

then I try to run it with the command
```python
python -m metaseq.scripts.reshard_fsdp \
        --input-glob-pattern "/root/data/OPT/1.3b/reshard-model_part-*.pt" \
        --output-shard-name "/root/data/OPT/1.3b/new.pt" \
        --num-output-shards 1 --skip-optimizer-state True --unflatten-weights True
```
I get the following errors,
```
Traceback (most recent call last):
  File "/usr/local/python3.8/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/python3.8/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/shangyw/OPT_ENV/metaseq-main/metaseq/scripts/reshard_fsdp.py", line 242, in <module>
    fire.Fire(reshard_fsdp_checkpoints)
  File "/home/shangyw/virtualenv/p3.8/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/shangyw/virtualenv/p3.8/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/shangyw/virtualenv/p3.8/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/shangyw/OPT_ENV/metaseq-main/metaseq/scripts/reshard_fsdp.py", line 53, in reshard_fsdp_checkpoints
    resharded_state_dicts = reshard_fsdp_state_dicts(
  File "/home/shangyw/OPT_ENV/metaseq-main/metaseq/scripts/reshard_fsdp.py", line 76, in reshard_fsdp_state_dicts
    shard_metadata=[s["shard_metadata"] for s in shard_state_dicts],
  File "/home/shangyw/OPT_ENV/metaseq-main/metaseq/scripts/reshard_fsdp.py", line 76, in <listcomp>
    shard_metadata=[s["shard_metadata"] for s in shard_state_dicts],
KeyError: 'shard_metadata'

```
Are there any steps wrong?Thanks in a advance.

**Comment by tangbinh** [comment]
The downloaded checkpoint (i.e. `reshard-model_part-0.pt` and `reshard-model_part-1.pt`) have already been consolidated, so there is no need to run the `reshard_fsdp` script in this case.

To load these files with `metaseq-api-local` (i.e. [this script](https://github.com/facebookresearch/metaseq/blob/9ccd67c424927268eaa2e0c9ac0fa42e45590eff/metaseq/cli/interactive_hosted.py)), you simply need to make some config changes to include [a path](https://github.com/facebookresearch/metaseq/blob/9ccd67c424927268eaa2e0c9ac0fa42e45590eff/metaseq/service/constants.py#L37) to this checkpoint (e.g. setting `MODEL_FILE` to `/root/data/OPT/1.3b/reshard.pt`). For more information, please see [this README file](https://github.com/facebookresearch/metaseq/tree/main/metaseq/cli).

**Comment by tangbinh** [comment]
It's been a while without any update, so I'm closing the issue now. @upwindflys Please reopen it if you need further support.
