### ISSUE TITLE
pre-training script faild

### ISSUE THREAD

**Issue by hisashi-ito** [facebookresearch/metaseq#666]
## pre-training script faild
I want to pre-train  Japanese metaseq model.  The script for pre-training use the  following

* https://github.com/facebookresearch/metaseq/blob/main/docs/training.md
```shell
metaseq-train --task streaming_language_modeling \
  data-bin/pile-00 \
  --vocab-filename data-bin/pile-00/bpe-vocab.json \
  --merges-filename data-bin/pile-00/bpe-merges.txt \
  --criterion cross_entropy \
  --batch-size 8 \
  --save-dir /checkpoints/lm_transformer_pile-00 \
  --arch transformer_lm --share-decoder-input-output-embed \
  --dropout 0.1 \
  --optimizer adam --weight-decay 0.01 --clip-norm 0.0 \
  --lr 0.0005 --lr-scheduler inverse_sqrt --warmup-updates 4000 --warmup-init-lr 1e-07 \
  --tokens-per-sample 1024 --sample-break-mode none --fp16 \
  --aim-repo /path/to/log/dir
```
But, pre-training don't start ! 
* error code
 
```
Traceback (most recent call last):
  File "/usr/local/bin/metaseq-train", line 33, in <module>
    sys.exit(load_entry_point('metaseq', 'console_scripts', 'metaseq-train')())
  File "/build/metaseq/metaseq/cli/train.py", line 789, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/build/metaseq/metaseq/distributed/utils.py", line 287, in call_main
    return _spawn_helper(main, cfg, kwargs)
  File "/build/metaseq/metaseq/distributed/utils.py", line 265, in _spawn_helper
    retval = distributed_main(-1, main, cfg, kwargs)
  File "/build/metaseq/metaseq/distributed/utils.py", line 227, in distributed_main
    retval = main(cfg, **kwargs)
  File "/build/metaseq/metaseq/cli/train.py", line 132, in main
    model = task.build_model(cfg.model)
  File "/build/metaseq/metaseq/tasks/base_task.py", line 532, in build_model
    model = models.build_model(args, self)
  File "/build/metaseq/metaseq/models/__init__.py", line 82, in build_model
    return model.build_model(cfg, task)
  File "/build/metaseq/metaseq/models/base_model.py", line 53, in build_model
    raise NotImplementedError("Model must implement the build_model method")
NotImplementedError: Model must implement the build_model method
```
I think the reason is that  `metaseq/metaseq/models/transformer_lm.base_model` method  is not implemented. 

https://github.com/facebookresearch/metaseq/blob/b47f8d115516b539ba0e5002aa3ab707ad10a792/metaseq/models/transformer_lm.py#L197-L200

Can you tell me how to solve it?
 - metaseq Version
   latest version
    ```
   commit b47f8d115516b539ba0e5002aa3ab707ad10a792 (HEAD -> main, origin/main, origin/HEAD)
   Author: Susan Zhang <suchenzang@users.noreply.github.com>
   Date:   Sat Feb 25 07:12:34 2023 -0500
   ```

**Comment by SefaZeng** [comment]
Any new here? I met the same problem.

**Comment by hisashi-ito** [comment]
@SefaZeng 
> Any new here?

no　:(

**Comment by GongZhengLi** [comment]
change the --arch , the default arch is a abstract class, use a specific one.

**Comment by punitkoura** [comment]
@hisashi-ito Could you refer to the changes made in #686 and see if they fix your issue? You can also try other model architectures like transformer_lm_megatron - these are defined in metaseq/models/transformer_lm.py

**Comment by punitkoura** [comment]
Please feel free to reopen if this is still not solved. Thanks!

**Comment by Rongjiehuang** [comment]
Hi, could you please tell me where to download the dataset data-bin/pile-00 with vocab and merges
