### ISSUE TITLE
Unable to run interactive_hosted locally 

### ISSUE THREAD

**Issue by suchenzang** [facebookresearch/metaseq#70]
To reproduce:
* ssh to node 131 on cluster
* confirm that mp 175B shards exist in `/mnt/scratch/175B/reshard_no_os/`
* permissions on dir has been opened to all (chmod 777)
* metaseq is on main

Resulting stacktrace:
```
(metaseq-test-apr7) susanz@<node 131 on cluster>:~/staging/metaseq$ python -m metaseq_cli.interactive_hosted
2022-05-08 20:09:42 | INFO | metaseq_cli.interactive | Local checkpoint copy already exists, skipping copy
2022-05-08 20:09:42 | INFO | metaseq.tasks.language_modeling | dictionary: 50272 types
2022-05-08 20:09:42 | INFO | metaseq.hub_utils | loading model(s) from /mnt/scratch/175B/reshard_no_os/reshard.pt
Traceback (most recent call last):
  File "/shared/home/susanz/miniconda3/envs/metaseq-test-apr7/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/shared/home/susanz/miniconda3/envs/metaseq-test-apr7/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/shared/home/susanz/staging/metaseq/metaseq_cli/interactive_hosted.py", line 304, in <module>
    cli_main()
  File "/shared/home/susanz/staging/metaseq/metaseq_cli/interactive_hosted.py", line 300, in cli_main
    dist_utils.call_main(cfg, worker_main, namespace_args=args)
  File "/shared/home/susanz/staging/metaseq/metaseq/distributed/utils.py", line 263, in call_main
    return main(cfg, **kwargs)
  File "/shared/home/susanz/staging/metaseq/metaseq_cli/interactive_hosted.py", line 156, in worker_main
    models = generator.load_model()  # noqa: F841
  File "/shared/home/susanz/staging/metaseq/metaseq/hub_utils.py", line 485, in load_model
    models, _model_args, _task = checkpoint_utils.load_model_ensemble_and_task(
  File "/shared/home/susanz/staging/metaseq/metaseq/checkpoint_utils.py", line 473, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/shared/home/susanz/staging/metaseq/metaseq/checkpoint_utils.py", line 408, in load_checkpoint_to_cpu
    paths_to_load = get_paths_to_load(local_path, suffix="shard")
  File "/shared/home/susanz/staging/metaseq/metaseq/checkpoint_utils.py", line 348, in get_paths_to_load
    if not _is_checkpoint_sharded(checkpoint_files):
  File "/shared/home/susanz/staging/metaseq/metaseq/checkpoint_utils.py", line 339, in _is_checkpoint_sharded
    size_ratio = max(sizes) / min(sizes)
ValueError: max() arg is an empty sequence
```

@stephenroller last time we saw this, it seemed to be a read permissions issue?

**Comment by suchenzang** [comment]
Model seems to load fine via slurm srun?  How can we confirm it came up correctly?
```
(metaseq-test-apr7) susanz@<login node>:~/staging/metaseq$ srun --ntasks-per-node 1 --gpus-per-node 8 --nodes 1 --c
pus-per-task 8 --mem 400gb \
>     --quit-on-interrupt --job-name genwork \
>     python3 -m metaseq_cli.interactive_hosted

2022-05-08 20:14:22 | INFO | metaseq_cli.interactive | Local checkpoint copy already exists, skipping copy
2022-05-08 20:14:23 | INFO | metaseq.distributed.utils | distributed init (rank 0): tcp://<node 131>:13000
2022-05-08 20:14:29 | INFO | metaseq.distributed.utils | distributed init (rank 2): tcp://<node 131>:13000
...
2022-05-08 20:16:52 | INFO | metaseq.checkpoint_utils | Done loading state dict
2022-05-08 20:16:54 | INFO | metaseq_cli.interactive | loaded model 0
2022-05-08 20:16:54 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:12 to store for rank: 0
2022-05-08 20:16:54 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:12 with 8 nodes.
2022-05-08 20:17:01 | INFO | metaseq_cli.interactive | Worker engaged! 10.30.4.87:6010
 * Serving Flask app 'interactive_hosted' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2022-05-08 20:17:01 | INFO | werkzeug |  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:6010
 * Running on http://10.30.4.87:6010 (Press CTRL+C to quit)
```

**Comment by BlackSamorez** [comment]
What ```constants.py``` do you use? Try changing ```distributed_port``` (13000 by default) to -1

**Comment by stephenroller** [comment]
Did you ssh directly or allocate the node in slurm?

**Comment by suchenzang** [comment]
Ahh that does it. The repro is with ssh'ing directly, not allocating via srun.  With srun allocation, can run `python -m metaseq_cli.interactive_hosted` without any issues.

**Comment by mayank31398** [comment]
I am still getting this issue.
Local spawning is not working for 2.7B parameter model
I am not using any scheduler
This is the constants.py I am using:
```
# Copyright (c) Meta Platforms, Inc. and affiliates. All Rights Reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

import os

MAX_SEQ_LEN = 2048
BATCH_SIZE = 2048  # silly high bc we dynamically batch by MAX_BATCH_TOKENS
MAX_BATCH_TOKENS = 3072
DEFAULT_PORT = 6010
MODEL_PARALLEL = 4
TOTAL_WORLD_SIZE = 4
MAX_BEAM = 16

try:
    # internal logic denoting where checkpoints are in meta infrastructure
    from metaseq_internal.constants import CHECKPOINT_FOLDER
except ImportError:
    # CHECKPOINT_FOLDER should point to a shared drive (e.g. NFS) where the
    # checkpoints from S3 are stored. As an example:
    # CHECKPOINT_FOLDER = "/example/175B/reshard_no_os"
    # $ ls /example/175B/reshard_no_os
    # reshard-model_part-0.pt
    # reshard-model_part-1.pt
    # reshard-model_part-2.pt
    # reshard-model_part-3.pt
    # reshard-model_part-4.pt
    # reshard-model_part-5.pt
    # reshard-model_part-6.pt
    # reshard-model_part-7.pt
    CHECKPOINT_FOLDER = "checkpoints"

# tokenizer files
BPE_MERGES = os.path.join(CHECKPOINT_FOLDER, "gpt2-merges.txt")
BPE_VOCAB = os.path.join(CHECKPOINT_FOLDER, "gpt2-vocab.json")
MODEL_FILE = os.path.join(CHECKPOINT_FOLDER, "reshard.pt")


LAUNCH_ARGS = [
    f"--model-parallel-size {MODEL_PARALLEL}",
    f"--distributed-world-size {TOTAL_WORLD_SIZE}",
    "--task language_modeling",
    f"--bpe-merges {BPE_MERGES}",
    f"--bpe-vocab {BPE_VOCAB}",
    "--bpe hf_byte_bpe",
    f"--merges-filename {BPE_MERGES}",  # TODO(susanz): hack for getting interactive_hosted working on public repo
    f"--vocab-filename {BPE_VOCAB}",  # TODO(susanz): hack for getting interactive_hosted working on public repo
    f"--path {CHECKPOINT_FOLDER}/reshard.pt",
    "--beam 1 --nbest 1",
    "--distributed-port 13000",
    "--checkpoint-shard-count 1",
    "--use-sharded-state",
    f"--batch-size {BATCH_SIZE}",
    f"--buffer-size {BATCH_SIZE * MAX_SEQ_LEN}",
    f"--max-tokens {BATCH_SIZE * MAX_SEQ_LEN}",
    "/tmp",  # required "data" argument.
]

```

**Comment by badcode6** [comment]
this problem still exists.
