### ISSUE TITLE
Runtime error in CLI

### ISSUE THREAD

**Issue by Mrs-Hudson** [facebookresearch/metaseq#71]
Hi I am running the CLI and querying it in an adhoc fashion using the code below:
`import requests
import json
from flask import  jsonify

url = 'https://127.0.0.1:6010/completions'
headers = {'Content-Type': 'application/json'}

filters = {'prompt':'LinkedIn is a great company2'}
#print(jsonify(filters))
#params = dict(json=json.dumps(filters))
print(filters)
print(json.dumps(filters))
response = requests.post(url, json=filters,headers=headers,verify=False)
#print(response.text)
assert response.status_code == 200
print(response.json())`
I see the error below:
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/azureuser/metaseq/metaseq_cli/interactive_hosted.py", line 89, in batching_loop
    item = target_queue.get(timeout=timeout / 1000)
  File "/anaconda/envs/azureml_py38/lib/python3.8/queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/anaconda/envs/azureml_py38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/azureuser/metaseq/metaseq_cli/interactive_hosted.py", line 131, in batching_loop
    generations = generator.generate(**request_object)
  File "/home/azureuser/metaseq/metaseq/hub_utils.py", line 568, in generate
    dataset=self.task.build_dataset_for_inference(tokens, lengths),
  File "/home/azureuser/metaseq/metaseq/tasks/language_modeling.py", line 273, in build_dataset_for_inference
    TokenBlockDataset(
  File "/home/azureuser/metaseq/metaseq/data/token_block_dataset.py", line 62, in __init__
    _sizes, block_to_dataset_index, slice_indices = self._build_slice_indices(
  File "/home/azureuser/metaseq/metaseq/data/token_block_dataset.py", line 92, in _build_slice_indices
    from metaseq.data.token_block_utils_fast import (
  File "metaseq/data/token_block_utils_fast.pyx", line 1, in init metaseq.data.token_block_utils_fast
    # cython: language_level=3
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject`

 - metaseq Version (e.g., 1.0 or master): 0.0.1
 - PyTorch Version (e.g., 1.0): '1.10.1+cu113'
 - OS (e.g., Linux): Linux
 `NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic`
 - How you installed metaseq (`pip`, source): Same as setup instructions
 - Build command you used (if compiling from source): Same as setup instructions
 - Python version:  3.8.5
 - CUDA/cuDNN version: 
 `(azureml_py38) azureuser@rparik4:~/metaseq$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0`

 - GPU models and configuration:  Azure compute node with 8 gpus
 Virtual machine size
Standard_ND40rs_v2 (40 cores, 672 GB RAM, 2900 GB disk)
Processing unit
[GPU - 8 x NVIDIA Tesla V100](https://www.nvidia.com/en-us/data-center/v100)
 - Any other relevant information:

**Comment by BlackSamorez** [comment]
Try ```pip install --upgrade numpy```. Fixed it for me

**Comment by Mrs-Hudson** [comment]
Thanks this worked for me!
