### ISSUE TITLE
CLI times out with 350 M 

### ISSUE THREAD

**Issue by Mrs-Hudson** [facebookresearch/metaseq#86]
## 🐛 Bug
When I launch the interactive hosted CLI with the 350M parameter model, the server logs show timeout without the server up and running (logs below)

### To Reproduce

Running python -m metaseq_cli.interactive_hosted with 350M parameter OPT model

`2022-05-10 05:09:38 | INFO | metaseq_cli.interactive | Local checkpoint copy already exists, skipping copy
2022-05-10 05:09:39 | INFO | metaseq.distributed.utils | distributed init (rank 0): tcp://localhost:19587
2022-05-10 05:09:41 | INFO | metaseq.distributed.utils | distributed init (rank 2): tcp://localhost:19587
2022-05-10 05:09:41 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:1 to store for rank: 2
2022-05-10 05:09:41 | INFO | metaseq.distributed.utils | distributed init (rank 1): tcp://localhost:19587
2022-05-10 05:09:41 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:1 to store for rank: 1
2022-05-10 05:09:41 | INFO | torch.distributed.distributed_c10d | Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
2022-05-10 05:09:41 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:1 to store for rank: 0
2022-05-10 05:09:51 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:09:51 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:10:01 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
.
.
2022-05-10 05:39:33 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 05:39:33 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/azureuser/metaseq/metaseq_cli/interactive_hosted.py", line 308, in <module>
    cli_main()
  File "/home/azureuser/metaseq/metaseq_cli/interactive_hosted.py", line 304, in cli_main
    dist_utils.call_main(cfg, worker_main, namespace_args=args)
  File "/home/azureuser/metaseq/metaseq/distributed/utils.py", line 256, in call_main
    return _spawn_helper(main, cfg, kwargs)
  File "/home/azureuser/metaseq/metaseq/distributed/utils.py", line 234, in _spawn_helper
    retval = distributed_main(-1, main, cfg, kwargs)
  File "/home/azureuser/metaseq/metaseq/distributed/utils.py", line 198, in distributed_main
    cfg.distributed_training.distributed_rank = distributed_init(cfg)
  File "/home/azureuser/metaseq/metaseq/distributed/utils.py", line 136, in distributed_init
    dist.init_process_group(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 608, in init_process_group
    _store_based_barrier(rank, store, timeout)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 244, in _store_based_barrier
    raise RuntimeError(
RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 17:17:18 | INFO | metaseq_cli.interactive | Local checkpoint copy already exists, skipping copy`
 If I i crease the world size and model parallel to 3, the worker count is 4

metaseq Version (e.g., 1.0 or master): 0.0.1

PyTorch Version (e.g., 1.0): '1.10.1+cu113'

OS (e.g., Linux): Linux
NAME="Ubuntu" VERSION="18.04.6 LTS (Bionic Beaver)" ID=ubuntu ID_LIKE=debian PRETTY_NAME="Ubuntu 18.04.6 LTS" VERSION_ID="18.04" HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" VERSION_CODENAME=bionic UBUNTU_CODENAME=bionic

How you installed metaseq (pip, source): Same as setup instructions

Build command you used (if compiling from source): Same as setup instructions

Python version: 3.8.5

CUDA/cuDNN version:
(azureml_py38) azureuser@rparik4:~/metaseq$ nvcc --version nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2021 NVIDIA Corporation Built on Sun_Feb_14_21:12:58_PST_2021 Cuda compilation tools, release 11.2, V11.2.152 Build cuda_11.2.r11.2/compiler.29618528_0

GPU models and configuration: Azure compute node with 8 gpus
Virtual machine size
Standard_ND40rs_v2 (40 cores, 672 GB RAM, 2900 GB disk)
Processing unit
[GPU - 8 x NVIDIA Tesla V100](https://www.nvidia.com/en-us/data-center/v100)

**Comment by stephenroller** [comment]
This may be related to #79

**Comment by Mrs-Hudson** [comment]
Thanks, I made that change , but it seems to hang now. Should the model_parallel for 350M mdoel be 1 or 2?
Logs
`2022-05-10 18:55:00 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 18:55:10 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 18:55:20 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 18:55:30 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 18:55:40 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 18:55:50 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
2022-05-10 18:56:00 | INFO | torch.distributed.distributed_c10d | Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=2, worker_count=3, timeout=0:30:00)
Killed
/anaconda/envs/azureml_py38/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 4 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
2022-05-10 18:57:46 | INFO | metaseq_cli.interactive | Local checkpoint copy already exists, skipping copy
2022-05-10 18:57:47 | INFO | metaseq.distributed.utils | distributed init (rank 0): tcp://localhost:16964
2022-05-10 18:57:49 | INFO | metaseq.distributed.utils | distributed init (rank 1): tcp://localhost:16964
2022-05-10 18:57:49 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:1 to store for rank: 1
2022-05-10 18:57:49 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:1 to store for rank: 0
2022-05-10 18:57:49 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
2022-05-10 18:57:49 | INFO | metaseq.distributed.utils | initialized host rparik4 as rank 0
2022-05-10 18:57:49 | INFO | torch.distributed.distributed_c10d | Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
2022-05-10 18:57:49 | INFO | metaseq.distributed.utils | initialized host rparik4 as rank 1
> initializing tensor model parallel with size 2
> initializing pipeline model parallel with size 1
2022-05-10 18:57:53 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:2 to store for rank: 0
2022-05-10 18:57:53 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:2 with 2 nodes.
2022-05-10 18:57:53 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:3 to store for rank: 0
2022-05-10 18:57:53 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:3 with 2 nodes.
2022-05-10 18:57:53 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:4 to store for rank: 0
2022-05-10 18:57:53 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:4 with 2 nodes.
2022-05-10 18:57:53 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:5 to store for rank: 0
2022-05-10 18:57:53 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:5 with 2 nodes.
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 2719 and data parallel seed: 1
Filenames are
['/home/azureuser/opt-models/175B/reshard_no_os/reshard.pt']
num shards is
1
Num shards 1

local path is: /home/azureuser/opt-models/175B/reshard_no_os/reshard-model_part-1.pt
checkpiunt files is:
[]
2022-05-10 18:57:53 | INFO | metaseq.tasks.language_modeling | dictionary: 50272 types
2022-05-10 18:57:53 | INFO | metaseq.hub_utils | loading model(s) from /home/azureuser/opt-models/175B/reshard_no_os/reshard.pt
Filenames are
['/home/azureuser/opt-models/175B/reshard_no_os/reshard.pt']
num shards is
1
Num shards 1

local path is: /home/azureuser/opt-models/175B/reshard_no_os/reshard-model_part-0.pt
checkpiunt files is:
['/home/azureuser/opt-models/175B/reshard_no_os/reshard-model_part-0.pt']
2022-05-10 18:57:54 | INFO | metaseq.checkpoint_utils | Done reading from disk
2022-05-10 18:57:54 | INFO | metaseq.modules.fused_bias_gelu | Compiling and loading fused kernels

NOTE: If this hangs here, your megatron fused kernels may be corrupted. This can happen if a previous job is interrupted during a build. In that case, delete the megatron build directory and relaunch training. The megatron build directory is located at: /home/azureuser/Megatron-LM/megatron/fused_kernels/build
Detected CUDA files, patching ldflags
Emitting ninja build file /home/azureuser/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_upper_triang_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_upper_triang_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/azureuser/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/azureuser/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module fused_mix_prec_layer_norm_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.`

**Comment by stephenroller** [comment]
There should be no model parallel (1) for the 350M. It might not work with the API rn either, I'm not sure: the API hard codes FSDP rn.

Note the warning about freezing and deleting the Megatron build. That bites me constantly and you might want to execute it.

**Comment by Mrs-Hudson** [comment]
Thanks! Which are the ones that could work with the API? With 125M the server is up and I can query it but sadly it returns gibberish

**Comment by Mrs-Hudson** [comment]
Actually I have access to the A100s on Azure in my company but I don't yet have the 175B model access. Have filled the form so let's see. Trying with the other models till then

**Comment by suchenzang** [comment]
Closing this issue as well with same comment as in: https://github.com/facebookresearch/metaseq/issues/94#issuecomment-1124547422

> @Mrs-Hudson going to close this issue given the immediate release of #88.
> 
> (Note in particular the conversion needed from [#88 (comment)](https://github.com/facebookresearch/metaseq/issues/88#issuecomment-1123591285)).
> 
> Judging from your `/home/azureuser/opt-models/175B/reshard_no_os/ ` directory, it seems like you've included many checkpoints there with various different naming conventions for which checkpoint loading will not be able to recognize. There is another open task to clean up this logic so that it is clearer to users how model loading should work: #78 .
