### ISSUE TITLE
[BUG] Running baseline will give path error

### ISSUE THREAD

**Issue by Leli1024** [facebookresearch/metaseq#91]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 'pt-baselines -n 2 -g 8 -p test_v0 --model-size 125m --azure --checkpoints-dir "model_ckpts" --no-save-dir # Remove this if you want to print out full save-dir pathopt-baselines'
2. See error
`Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/studiolab/bin/opt-baselines", line 33, in <module>
    sys.exit(load_entry_point('metaseq', 'console_scripts', 'opt-baselines')())
  File "/home/studio-lab-user/metaseq/metaseq/launcher/opt_baselines.py", line 315, in cli_main
    sweep_main(
  File "/home/studio-lab-user/metaseq/metaseq/launcher/sweep.py", line 378, in main
    backend_main(get_grid, postprocess_hyperparams, args)
  File "/home/studio-lab-user/metaseq/metaseq/launcher/slurm.py", line 34, in main
    grid = get_grid(args)
  File "/home/studio-lab-user/metaseq/metaseq/launcher/opt_baselines.py", line 80, in get_grid
    raise RuntimeError("Where are you running this?! Check DATA_LOCATIONS.")
RuntimeError: Where are you running this?! Check DATA_LOCATIONS.`

### Environment

 - metaseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0) The version specified within the setup.MD file
 - OS (e.g., Linux, Windows, MacOS): linux (AWS)
 - How you installed metaseq (`pip`, source): pip3

### Additional context

As to another issue I reported, I had to manually modify the environment variables to direct to the user

**Comment by suchenzang** [comment]
Related to https://github.com/facebookresearch/metaseq/issues/77
