### ISSUE TITLE
Error running CLI with 30B : UnboundLocalError: local variable 'state' referenced before assignment

### ISSUE THREAD

**Issue by Mrs-Hudson** [facebookresearch/metaseq#94]
When I try to run the Metaseq CLI with the 30B model, I see the following error:
UnboundLocalError: local variable 'state' referenced before assignment

python -m metaseq_cli.interactive_hosted

`
2022-05-11 19:20:56 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:2 with 2 nodes.
2022-05-11 19:20:56 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:3 to store for rank: 0
2022-05-11 19:20:56 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:3 with 2 nodes.
2022-05-11 19:20:56 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:4 to store for rank: 0
2022-05-11 19:20:56 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:4 with 2 nodes.
2022-05-11 19:20:56 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:5 to store for rank: 0
2022-05-11 19:20:56 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:5 with 2 nodes.
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 2719 and data parallel seed: 1
2022-05-11 19:20:56 | INFO | metaseq.tasks.language_modeling | dictionary: 50272 types
2022-05-11 19:20:56 | INFO | metaseq.hub_utils | loading model(s) from /home/azureuser/opt-models/175B/reshard_no_os/reshard.pt
Filenames are
['/home/azureuser/opt-models/175B/reshard_no_os/reshard.pt']
num shards is
2
Num shards > 1

local path is: /home/azureuser/opt-models/175B/reshard_no_os/reshard_part0.pt
checkpiunt files is:
['/home/azureuser/opt-models/175B/reshard_no_os/reshard_part0.pt']
2022-05-11 19:21:10 | INFO | metaseq.checkpoint_utils | Done reading from disk
2022-05-11 19:21:11 | INFO | metaseq.modules.fused_bias_gelu | Compiling and loading fused kernels

NOTE: If this hangs here, your megatron fused kernels may be corrupted. This can happen if a previous job is interrupted during a build. In that case, delete the megatron build directory and relaunch training. The megatron build directory is located at: /home/azureuser/Megatron-LM/megatron/fused_kernels/build
Detected CUDA files, patching ldflags
Emitting ninja build file /home/azureuser/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_upper_triang_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_upper_triang_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/azureuser/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/azureuser/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module fused_mix_prec_layer_norm_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Filenames are
['/home/azureuser/opt-models/175B/reshard_no_os/reshard.pt']
num shards is
2
Num shards > 1

local path is: /home/azureuser/opt-models/175B/reshard_no_os/reshard_part0.pt
checkpiunt files is:
['/home/azureuser/opt-models/175B/reshard_no_os/reshard_part0.pt']
Loading extension module fused_mix_prec_layer_norm_cuda...
2022-05-11 19:21:13 | INFO | metaseq.modules.fused_bias_gelu | Done with compiling and loading fused kernels.
2022-05-11 19:21:19 | INFO | metaseq.checkpoint_utils | Done loading state dict
Num shards > 1

local path is: /home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt
checkpiunt files is:
['/home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt']
got exception while trying to load /home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt with paths to load ['/home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt']
2022-05-11 19:21:19 | INFO | metaseq.checkpoint_utils | Done reading from disk
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/azureuser/metaseq/metaseq_cli/interactive_hosted.py", line 308, in <module>
    cli_main()
  File "/home/azureuser/metaseq/metaseq_cli/interactive_hosted.py", line 304, in cli_main
    dist_utils.call_main(cfg, worker_main, namespace_args=args)
  File "/home/azureuser/metaseq/metaseq/distributed/utils.py", line 256, in call_main
    return _spawn_helper(main, cfg, kwargs)
  File "/home/azureuser/metaseq/metaseq/distributed/utils.py", line 234, in _spawn_helper
    retval = distributed_main(-1, main, cfg, kwargs)
  File "/home/azureuser/metaseq/metaseq/distributed/utils.py", line 203, in distributed_main
    main(cfg, **kwargs)
  File "/home/azureuser/metaseq/metaseq_cli/interactive_hosted.py", line 156, in worker_main
    models = generator.load_model()  # noqa: F841
  File "/home/azureuser/metaseq/metaseq/hub_utils.py", line 485, in load_model
    models, _model_args, _task = checkpoint_utils.load_model_ensemble_and_task(
  File "/home/azureuser/metaseq/metaseq/checkpoint_utils.py", line 481, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/azureuser/metaseq/metaseq/checkpoint_utils.py", line 426, in load_checkpoint_to_cpu
    if "cfg" in state and state["cfg"] is not None:
UnboundLocalError: local variable 'state' referenced before assignment`

**Environment**

metaseq Version (e.g., 1.0 or master): 0.0.1

PyTorch Version (e.g., 1.0): '1.10.1+cu113'

OS (e.g., Linux): Linux
NAME="Ubuntu" VERSION="18.04.6 LTS (Bionic Beaver)" ID=ubuntu ID_LIKE=debian PRETTY_NAME="Ubuntu 18.04.6 LTS" VERSION_ID="18.04" HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" VERSION_CODENAME=bionic UBUNTU_CODENAME=bionic

How you installed metaseq (pip, source): Same as setup instructions

Build command you used (if compiling from source): Same as setup instructions

Python version: 3.8.5

CUDA/cuDNN version:
(azureml_py38) azureuser@rparik4:~/metaseq$ nvcc --version nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2021 NVIDIA Corporation Built on Sun_Feb_14_21:12:58_PST_2021 Cuda compilation tools, release 11.2, V11.2.152 Build cuda_11.2.r11.2/compiler.29618528_0

GPU models and configuration: Azure compute node with 8 gpus
Virtual machine size
Standard_ND40rs_v2 (40 cores, 672 GB RAM, 2900 GB disk)
Processing unit
[GPU - 8 x NVIDIA Tesla V100](https://www.nvidia.com/en-us/data-center/v100)

**Comment by Mrs-Hudson** [comment]
If I add back the "--distributed-port 13000" , the model loads but then I get the error:
`Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/azureuser/metaseq/metaseq_cli/interactive_hosted.py", line 308, in <module>
    cli_main()
  File "/home/azureuser/metaseq/metaseq_cli/interactive_hosted.py", line 304, in cli_main
    dist_utils.call_main(cfg, worker_main, namespace_args=args)
  File "/home/azureuser/metaseq/metaseq/distributed/utils.py", line 263, in call_main
    return main(cfg, **kwargs)
  File "/home/azureuser/metaseq/metaseq_cli/interactive_hosted.py", line 156, in worker_main
    models = generator.load_model()  # noqa: F841
  File "/home/azureuser/metaseq/metaseq/hub_utils.py", line 485, in load_model
    models, _model_args, _task = checkpoint_utils.load_model_ensemble_and_task(
  File "/home/azureuser/metaseq/metaseq/checkpoint_utils.py", line 516, in load_model_ensemble_and_task
    model = build_model_hook(cfg, task)
  File "/home/azureuser/metaseq/metaseq/hub_utils.py", line 474, in _build_model
    model = task.build_model(cfg.model).half().cuda()
  File "/home/azureuser/metaseq/metaseq/tasks/language_modeling.py", line 164, in build_model
    model = super().build_model(args)
  File "/home/azureuser/metaseq/metaseq/tasks/base_task.py", line 560, in build_model
    model = models.build_model(args, self)
  File "/home/azureuser/metaseq/metaseq/models/__init__.py", line 89, in build_model
    return model.build_model(cfg, task)
  File "/home/azureuser/metaseq/metaseq/model_parallel/models/transformer_lm.py", line 47, in build_model
    embed_tokens = cls.build_embedding(
  File "/home/azureuser/metaseq/metaseq/model_parallel/models/transformer_lm.py", line 82, in build_embedding
    embed_tokens = VocabParallelEmbedding(
  File "/home/azureuser/Megatron-LM/megatron/mpu/layers.py", line 190, in __init__
    self.tensor_model_parallel_size = get_tensor_model_parallel_world_size()
  File "/home/azureuser/Megatron-LM/megatron/mpu/initialize.py", line 258, in get_tensor_model_parallel_world_size
    return torch.distributed.get_world_size(group=get_tensor_model_parallel_group())
  File "/home/azureuser/Megatron-LM/megatron/mpu/initialize.py", line 215, in get_tensor_model_parallel_group
    assert _TENSOR_MODEL_PARALLEL_GROUP is not None, \
AssertionError: intra_layer_model parallel group is not initialized`

I have set MODEL_PARALLEL and WORLD_SIZE as 2 for the 30B model

**Comment by suchenzang** [comment]
It looks like you hit some exception that got swallowed with a print statement, yielding the first error you see of 'state' being referenced before assignment:
```
got exception while trying to load /home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt with paths to load ['/home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt']
```
https://github.com/facebookresearch/metaseq/blob/be754b5e2d8c3c013cca456a11e827544f4a6247/metaseq/checkpoint_utils.py#L414

Could you print out what exception you're actually hitting here? And whether or not `/home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt` exists locally where you're running this?

**Comment by Mrs-Hudson** [comment]
Thanks Susan!

The exception is:
`2022-05-12 05:10:14 | INFO | metaseq_cli.interactive | Local checkpoint copy already exists, skipping copy
2022-05-12 05:10:14 | INFO | metaseq.distributed.utils | distributed init (rank 0): tcp://localhost:11881
2022-05-12 05:10:17 | INFO | metaseq.distributed.utils | distributed init (rank 1): tcp://localhost:11881
2022-05-12 05:10:17 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:1 to store for rank: 1
2022-05-12 05:10:17 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:1 to store for rank: 0
2022-05-12 05:10:17 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
2022-05-12 05:10:17 | INFO | metaseq.distributed.utils | initialized host rparik4 as rank 0
2022-05-12 05:10:17 | INFO | torch.distributed.distributed_c10d | Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
2022-05-12 05:10:17 | INFO | metaseq.distributed.utils | initialized host rparik4 as rank 1
> initializing tensor model parallel with size 2
> initializing pipeline model parallel with size 1
2022-05-12 05:10:21 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:2 to store for rank: 0
2022-05-12 05:10:21 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:2 with 2 nodes.
2022-05-12 05:10:21 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:3 to store for rank: 0
2022-05-12 05:10:21 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:3 with 2 nodes.
2022-05-12 05:10:21 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:4 to store for rank: 0
2022-05-12 05:10:21 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:4 with 2 nodes.
2022-05-12 05:10:21 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:5 to store for rank: 0
2022-05-12 05:10:21 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:5 with 2 nodes.
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 2719 and data parallel seed: 1
2022-05-12 05:10:21 | INFO | metaseq.tasks.language_modeling | dictionary: 50272 types
2022-05-12 05:10:21 | INFO | metaseq.hub_utils | loading model(s) from /home/azureuser/opt-models/175B/reshard_no_os/reshard.pt
Filenames are
['/home/azureuser/opt-models/175B/reshard_no_os/reshard.pt']
num shards is
2
Num shards > 1

local path is: /home/azureuser/opt-models/175B/reshard_no_os/reshard_part0.pt
checkpiunt files is:
['/home/azureuser/opt-models/175B/reshard_no_os/reshard_part0.pt']
Paths to load:
['/home/azureuser/opt-models/175B/reshard_no_os/reshard_part0.pt']
In else lenpaths_to_load > 1
In torch load cpu
/home/azureuser/opt-models/175B/reshard_no_os/reshard_part0.pt
returning from torch_load_cpu
2022-05-12 05:10:35 | INFO | metaseq.checkpoint_utils | Done reading from disk
2022-05-12 05:10:35 | INFO | metaseq.modules.fused_bias_gelu | Compiling and loading fused kernels

NOTE: If this hangs here, your megatron fused kernels may be corrupted. This can happen if a previous job is interrupted during a build. In that case, delete the megatron build directory and relaunch training. The megatron build directory is located at: /home/azureuser/Megatron-LM/megatron/fused_kernels/build
Detected CUDA files, patching ldflags
Emitting ninja build file /home/azureuser/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_upper_triang_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_upper_triang_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/azureuser/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/azureuser/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module fused_mix_prec_layer_norm_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Filenames are
['/home/azureuser/opt-models/175B/reshard_no_os/reshard.pt']
num shards is
2
Num shards > 1

local path is: /home/azureuser/opt-models/175B/reshard_no_os/reshard_part0.pt
checkpiunt files is:
['/home/azureuser/opt-models/175B/reshard_no_os/reshard_part0.pt']
Paths to load:
['/home/azureuser/opt-models/175B/reshard_no_os/reshard_part0.pt']
In else lenpaths_to_load > 1
In torch load cpu
/home/azureuser/opt-models/175B/reshard_no_os/reshard_part0.pt
returning from torch_load_cpu
Loading extension module fused_mix_prec_layer_norm_cuda...
2022-05-12 05:10:37 | INFO | metaseq.modules.fused_bias_gelu | Done with compiling and loading fused kernels.
Num shards > 1

local path is: /home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt
checkpiunt files is:
['/home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt']
Paths to load:
['/home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt']
In else lenpaths_to_load > 1
In torch load cpu
/home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt
PytorchStreamReader failed reading zip archive: failed finding central directory
got exception while trying to load /home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt with paths to load ['/home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt']
2022-05-12 05:10:46 | INFO | metaseq.checkpoint_utils | Done loading state dict
Num shards > 1

local path is: /home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt
checkpiunt files is:
['/home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt']
Paths to load:
['/home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt']
In else lenpaths_to_load > 1
**In torch load cpu
/home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt
PytorchStreamReader failed reading zip archive: failed finding central directory
got exception while trying to load /home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt with paths to load** ['/home/azureuser/opt-models/175B/reshard_no_os/reshard_part1.pt']
2022-05-12 05:10:46 | INFO | metaseq.checkpoint_utils | Done reading from disk
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/azureuser/metaseq/metaseq_cli/interactive_hosted.py", line 308, in <module>
    cli_main()
  File "/home/azureuser/metaseq/metaseq_cli/interactive_hosted.py", line 304, in cli_main
    dist_utils.call_main(cfg, worker_main, namespace_args=args)
  File "/home/azureuser/metaseq/metaseq/distributed/utils.py", line 256, in call_main
    return _spawn_helper(main, cfg, kwargs)
  File "/home/azureuser/metaseq/metaseq/distributed/utils.py", line 234, in _spawn_helper
    retval = distributed_main(-1, main, cfg, kwargs)
  File "/home/azureuser/metaseq/metaseq/distributed/utils.py", line 203, in distributed_main
    main(cfg, **kwargs)
  File "/home/azureuser/metaseq/metaseq_cli/interactive_hosted.py", line 156, in worker_main
    models = generator.load_model()  # noqa: F841
  File "/home/azureuser/metaseq/metaseq/hub_utils.py", line 485, in load_model
    models, _model_args, _task = checkpoint_utils.load_model_ensemble_and_task(
  File "/home/azureuser/metaseq/metaseq/checkpoint_utils.py", line 486, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/azureuser/metaseq/metaseq/checkpoint_utils.py", line 431, in load_checkpoint_to_cpu
    if "cfg" in state and state["cfg"] is not None:
UnboundLocalError: local variable 'state' referenced before assignment`

The contents of the reshard_no_os directory
`azureuser@rparik4:~/metaseq$ ls -lh  /home/azureuser/opt-models/175B/reshard_no_os/
total 67G
-rw-rw-r-- 1 azureuser azureuser 382K May  6 22:50 dict.txt
-rw-rw-r-- 1 azureuser azureuser 681M May  2 20:56 reshard_350M.pt
-rw-rw-r-- 1 azureuser azureuser  28G May  2 20:37 reshard_part0.pt
-rw-rw-r-- 1 azureuser azureuser 122M May  2 20:57 reshard_part0125M.pt
-rw-rw-r-- 1 azureuser azureuser 6.3G May  2 20:52 reshard_part06.7B.pt
-rw-rw-r-- 1 azureuser azureuser  25G May 11 19:07 reshard_part1.pt
-rw-rw-r-- 1 azureuser azureuser 122M May  2 20:57 reshard_part1125M.pt
-rw-rw-r-- 1 azureuser azureuser 6.3G May  2 20:53 reshard_part16.7B.pt`

**Comment by suchenzang** [comment]
@Mrs-Hudson  going to close this issue given the immediate release of https://github.com/facebookresearch/metaseq/issues/88.  

(Note in particular the conversion needed from https://github.com/facebookresearch/metaseq/issues/88#issuecomment-1123591285).

Judging from your `/home/azureuser/opt-models/175B/reshard_no_os/ ` directory, it seems like you've included many checkpoints there with various different naming conventions for which checkpoint loading will not be able to recognize.  There is another open task to clean up this logic so that it is clearer to users how model loading should work: https://github.com/facebookresearch/metaseq/issues/78 .
